// Copyright (c) Tech Soft 3D
//
// The information contained herein is confidential and proprietary to Tech Soft 3D, Inc.,
// and considered a trade secret as defined under civil and criminal statutes.
// Tech Soft 3D, Inc. shall pursue its civil and criminal remedies in the event of
// unauthorized use or misappropriation of its trade secrets.  Use of this information
// by anyone other than authorized employees of Tech Soft 3D, Inc. is granted only under
// a written non-disclosure agreement, expressly prescribing the scope and manner of such use.

#ifndef HIC_CALLS_DEFINED

/* Internal intermediate requests */

enum {
	IM_Device_Plane_Count,

	IM_New_Transform_Rendition,
	IM_New_Line_Rendition,
	IM_New_Edge_Rendition,
	IM_New_Face_Rendition,
	IM_New_Marker_Rendition,

	IM_New_Misc_Rendition,
	IM_New_Color_Map_Rendition,

	IM_Compute_Character_Position,
	IM_Compute_Xformed_Text_Pos,
	IM_Compute_Character_Width,
	IM_Determine_Text_Rotation,

	IM_Select_Segment,
	IM_Select_Window,
	IM_Record_Selection,

	IM_New_Marker,
	IM_New_Polyline,
	IM_New_Polygon,
	IM_New_Text,
	IM_Free_Geometry,

	IM_New_Tristrip,
	IM_Free_Tristrip,
	IM_New_Polyedge,
	IM_Free_Polyedge,
	IM_New_Polymarker,
	IM_Free_Polymarker,

	IM_Set_Naughty_Bit,
	IM_Clear_Naughty_Bit,

	IM_Abort_Update,

	IM_New_User_Face_Pattern,
	IM_Free_User_Face_Pattern,

	IM_Hard_Clip_Cutting_Planes,

	IM_New_User_Line_Pattern,
	IM_Free_User_Line_Pattern,

	IM_New_Polygonal_Clip_Region,
	IM_New_Complex_Clip_Region,

	IM_New_Vertex_Rendition,

	IM_Add_Cutting_Plane,
	IM_Remove_Cutting_Planes,

	IM_New_User_Line_Pattern_2,

	IM_Set_Z_Range,

	IM_Set_Marker_Symbol,
	IM_Set_Marker_Name,
	IM_Set_Vertex_Symbol,
	IM_Set_Vertex_Name,

	IM_Set_Line_Pattern,
	IM_Set_Line_Style,

	IM_Generate_Segment_Path,
	IM_Free_Segment_Path,

	IM_New_Text_Info,
	IM_Free_Text_Info,

	IM_Set_Edge_Pattern,
	IM_Set_Edge_Style,

	IM_New_Cut_Face_Rendition,
	IM_New_Cut_Edge_Rendition,

	IM_New_Geometry_Rendition,

	IM_New_Stencil_Bitmap,
	IM_Free_Stencil_Bitmap,

	IM_New_Visualization_Rendition,

	IM_Exit_Update,
	IM_Draw_Window,


	IM_Bash_Line_Color,
	IM_Bash_Line_Contrast_Color,
	IM_Bash_Edge_Color,
	IM_Bash_Edge_Contrast_Color,
	IM_Bash_Cut_Edge_Color,
	IM_Bash_Face_Color,
	IM_Bash_Face_Mirror_Color,
	IM_Bash_Cut_Face_Color,
	IM_Bash_Face_Back_Color,
	IM_Bash_Face_Contrast_Color,
	IM_Bash_Marker_Color,
	IM_Bash_Marker_Contrast_Color,
	IM_Bash_Vertex_Color,
	IM_Bash_Vertex_Contrast_Color,
	IM_Bash_Text_Color,
	IM_Bash_Text_Contrast_Color,

	IM_Abort_Selection,
	IM_Clear_Z_Buffer,

	IM_Occlusion_Query_Available,
	IM_Show_Driver_Segment_Key,
	IM_Show_Original_Driver_Segment_Key,


	IM_Show_Device_Type,
	IM_Show_Driver_Type,
	IM_Show_Device_Windowing_System,
	IM_Show_Device_Locater,
	IM_Show_Device_Locater_Button_Count,
	IM_Show_Device_Locater_Type,
	IM_Show_Device_Colors,
	IM_Show_Device_Max_Colors,
	IM_Show_Device_Pixels_X,
	IM_Show_Device_Pixels_Y,
	IM_Show_Device_Max_Pixels_X,
	IM_Show_Device_Max_Pixels_Y,
	IM_Show_Device_Window_ID,
	IM_Show_Device_Window_ID2,
	IM_Show_Device_Colormap_ID,
	IM_Show_Device_Z_Buffer_Depth,
	IM_Show_Device_Hardware_Lights,
	IM_Show_Device_Gouraud_Shading,
	IM_Show_Device_Phong_Shading,

	IM_Show_Line_Pattern,
	IM_Show_Line_Style,
	IM_Show_Line_Weight,

	IM_Show_Internal_Line_Color,
	IM_Show_Internal_Line_Contrast_Color,

	IM_Show_Internal_Edge_Color,
	IM_Show_Internal_Edge_Contrast_Color,

	IM_Show_Internal_Face_Color,
	IM_Show_Internal_Face_Contrast_Color,
	IM_Show_Internal_Face_Back_Color,

	IM_Show_Internal_Marker_Color,
	IM_Show_Internal_Marker_Contrast_Color,

	IM_Show_Internal_Vertex_Color,
	IM_Show_Internal_Vertex_Contrast_Color,

	IM_Show_Internal_Text_Color,

	IM_Show_Internal_Window_Color,
	IM_Show_Internal_Window_Contrast_Color,


	IM_Show_Polygon_Visibility,
	IM_Show_Edge_Pattern,
	IM_Show_Edge_Style,
	IM_Show_Edge_Weight,
	IM_Show_Face_Pattern,

	IM_Show_Marker_Symbol,
	IM_Show_Marker_Name,

	IM_Show_Text_Alignment,
	IM_Show_Text_Path,
	IM_Show_Text_Font_Size_Units,
	IM_Show_Text_Font_Size_Tol_Units,
	IM_Show_Text_Font_Extra_Space_Units,
	IM_Show_Text_Font_ID,
	IM_Show_Text_Font_Name,
	IM_Show_Text_Font_Transform,
	IM_Show_Text_Font_Index,
	IM_Show_Text_KIndex,
	IM_Show_Text_KInfo,
	IM_Show_Text_KInfo_At_Index,
	IM_Show_KInfo_Position,
	IM_Show_KInfo_Point,

	IM_Show_Text_String,
	IM_Show_Text_Length,
	IM_Show_Text_Char_Encoding,
	IM_Show_Text_Line_Count,
	IM_Show_Text_Line_Index,
	IM_Show_Text_Counts,
			
	IM_Show_Text_Position,
	IM_Show_Text_Reference,
	IM_Show_3D_Text_Position,
	IM_Show_Text_Baseline,
	IM_Show_Text_Longest_Baseline,
	IM_Show_Text_Char_Horizontal,
	IM_Show_Text_Char_Vertical,
	IM_Show_Text_Next_Line,

	IM_Show_Camera_Position,
	IM_Show_Camera_Target,
	IM_Show_Camera_Up_Vector,
	IM_Show_Camera_Projection,

	IM_Show_Z_Buffering,
	IM_Show_Window_Extent,
	IM_Show_Clipping,
	IM_Show_Hidden_Surfaces,
	//IM_Show_Visibility,

	IM_Show_Window_Pattern,

	IM_Show_Geometry,
	IM_Show_Geometry_Key,
	IM_Show_Original_Geometry_Key,
	IM_Show_Geometry_Type,
	IM_Partial_Erasing,

	IM_Show_Callback_Data,

	IM_Set_Line_Weight,
	IM_Set_Variable_Line_Weight,
	IM_Set_User_Line_Pattern,
	IM_Set_Internal_Line_Color,
	IM_Set_Edge_Weight,
	IM_Set_Variable_Edge_Weight,
	IM_Set_User_Edge_Pattern,
	IM_Set_Internal_Edge_Color,
	IM_Set_Face_Pattern,

	IM_Set_Window_Pattern,
	IM_Set_User_Face_Pattern,
	IM_Set_User_Window_Pattern,

	IM_Set_Internal_Face_Color,
	IM_Set_Internal_Face_Back_Color,
	IM_Set_Internal_Face_Contrast_Color,
	IM_Set_Face_Transmission_Color,
	IM_Set_Marker_Size,
	IM_Set_Variable_Marker_Size,
	IM_Set_Vertex_Size,
	IM_Set_Variable_Vertex_Size,
	IM_Set_Internal_Marker_Color,
	IM_Set_Internal_Vertex_Color,
	IM_Set_Text_Transform,
	IM_Set_Text_Size,
	IM_Set_Text_Size_Units,
	IM_Set_Text_Size_Tolerance,
	IM_Set_Text_Size_Tolerance_Units,
	IM_Set_Text_Extra_Space,
	IM_Set_Text_Extra_Space_Units,
	IM_Set_Text_Alignment,
	IM_Set_Text_Spacing,
	IM_Set_Text_Path,
	IM_Set_Text_Rotation,
	IM_Set_Text_Rotation_Follow_Path,
	IM_Set_Text_Width_Scale,
	IM_Set_Text_Slant,
	IM_Set_Internal_Text_Color,
	IM_Set_Text_Position,
	IM_Set_Text_Reference,
	IM_Set_3D_Text_Position,
	IM_Set_Text_Font_Index,
	IM_Set_Text_KIndex,
	IM_Set_Text_KInfo,
	IM_Set_Text_Line_Index,
	IM_Set_KInfo_Position,
	IM_Set_KInfo_Point, 
	IM_Set_KInfo_String_Width, 
	IM_Set_KInfo_String_Height, 
	IM_Set_KInfo_String_X, 
	IM_Set_KInfo_String_Y, 
	IM_Set_KInfo_Screen_Width, 
	IM_Set_KInfo_Screen_Height, 
	IM_Set_KInfo_Screen_X, 
	IM_Set_KInfo_Screen_Y, 
	IM_Set_KInfo_Flags, 

	IM_Set_Window_Color,
	IM_Set_Internal_Window_Color,
	IM_Set_Window_Contrast_Color,
	IM_Set_Internal_Window_Contrast_Color,
	IM_Set_Color_Map_Start,
	IM_Set_Face_Displacement,
	IM_Set_General_Displacement,
	IM_Set_Clipping,
	IM_Restrict_Clipping,
	IM_Set_Clip_Region,

	//IM_Set_Visibility,
	IM_Show_Marker_Position,
	IM_Show_Polyline_Count,
	IM_Show_Polyline_Points,
	IM_Show_Polygon_Count,
	IM_Show_Polygon_Points,
	IM_Set_LOD_Clamp,

	IM_Show_Selection_Point,
	IM_Show_Selection_Volume,
	IM_Show_Selection_Status,
	IM_Show_Selection_Action,

	IM_Set_Segment_Interesting,
	IM_UnSet_Segment_Interesting,
	IM_Check_Segment_Interesting,
	IM_Set_Geometry_Interesting,
	IM_UnSet_Geometry_Interesting,
	IM_Check_Geometry_Interesting,
	IM_Set_Current_Geometry_Interesting,
	IM_UnSet_Current_Geometry_Interesting,
	IM_Check_Current_Geometry_Interesting,

	IM_Show_Tristrip_Points,
	IM_Set_Tristrip_Points,
	IM_Show_Tristrip_Point_Count,
	IM_Show_Tristrip_Face_Count,
	IM_Show_Tristrip_Strips,
	IM_Set_Tristrip_Strips,
	IM_Show_Tristrip_Lengths,
	IM_Set_Tristrip_Lengths,
	IM_Show_Tristrip_Vertex_Indices,
	IM_Set_Tristrip_Vertex_Indices,
	IM_Show_Tristrip_Face_Indices,
	IM_Set_Tristrip_Face_Indices,
	IM_Show_Tristrip_Face_Colors,
	IM_Set_Tristrip_Face_Colors,
	IM_Show_Tristrip_Face_Normals,
	IM_Set_Tristrip_Face_Normals,
	IM_Show_Tristrip_Vertex_Colors,
	IM_Set_Tristrip_Vertex_Colors,
	IM_Show_Tristrip_Vertex_Findices,
	IM_Set_Tristrip_Vertex_Findices,
	IM_Show_Tristrip_Vertex_Normals,
	IM_Set_Tristrip_Vertex_Normals,
	IM_Show_Tristrip_Vertex_Parameters,
	IM_Set_Tristrip_Vertex_Parameters,
	IM_Show_Tristrip_Vertex_Parameter_Width,
	IM_Set_Tristrip_Vertex_Parameter_Width,
	IM_Show_Tristrip_Findex_Color_Interpolation,
	IM_Set_Tristrip_Findex_Color_Interpolation,

	IM_Show_Polyedge_Points,
	IM_Set_Polyedge_Points,
	IM_Show_Polyedge_Point_Count,
	IM_Show_Polyedge_Edge_Count,
	IM_Show_Polyedge_Strips,
	IM_Set_Polyedge_Strips,
	IM_Show_Polyedge_Lengths,
	IM_Set_Polyedge_Lengths,
	IM_Show_Polyedge_Vertex_Indices,
	IM_Set_Polyedge_Vertex_Indices,
	IM_Show_Polyedge_Edge_Indices,
	IM_Set_Polyedge_Edge_Indices,
	IM_Show_Polyedge_Edge_Colors,
	IM_Set_Polyedge_Edge_Colors,
	IM_Show_Polyedge_Edge_Normals,
	IM_Set_Polyedge_Edge_Normals,
	IM_Show_Polyedge_Vertex_Colors,
	IM_Set_Polyedge_Vertex_Colors,
	IM_Show_Polyedge_Vertex_Findices,
	IM_Set_Polyedge_Vertex_Findices,
	IM_Show_Polyedge_Vertex_Normals,
	IM_Set_Polyedge_Vertex_Normals,
	IM_Show_Polyedge_Vertex_Parameters,
	IM_Set_Polyedge_Vertex_Parameters,
	IM_Show_Polyedge_Vertex_Parameter_Width,
	IM_Set_Polyedge_Vertex_Parameter_Width,
	IM_Show_Polyedge_Findex_Color_Interpolation,
	IM_Set_Polyedge_Findex_Color_Interpolation,

	IM_Show_Polymarker_Points,
	IM_Set_Polymarker_Points,
	IM_Show_Polymarker_Point_Count,
	IM_Show_Polymarker_Length,
	IM_Set_Polymarker_Length,
	IM_Show_Polymarker_Vertex_Indices,
	IM_Set_Polymarker_Vertex_Indices,
	IM_Show_Polymarker_Vertex_Colors,
	IM_Set_Polymarker_Vertex_Colors,
	IM_Show_Polymarker_Vertex_Findices,
	IM_Set_Polymarker_Vertex_Findices,
	IM_Show_Polymarker_Vertex_Normals,
	IM_Set_Polymarker_Vertex_Normals,
	IM_Show_Polymarker_Vertex_Parameters,
	IM_Set_Polymarker_Vertex_Parameters,
	IM_Show_Polymarker_Vertex_Parameter_Width,
	IM_Set_Polymarker_Vertex_Parameter_Width,
	IM_Show_Polymarker_Findex_Color_Interpolation,
	IM_Set_Polymarker_Findex_Color_Interpolation,

	IM_Show_Color_Front_Locks,
	IM_Show_Color_Back_Locks,
	//IM_Show_Color_Face_Contrast_Locks,
	IM_Show_Color_Edge_Locks,
	//IM_Show_Color_Edge_Contrast_Locks,
	IM_Show_Color_Line_Locks,
	//IM_Show_Color_Line_Contrast_Locks,
	IM_Show_Color_Marker_Locks,
	//IM_Show_Color_Marker_Contrast_Locks,
	IM_Show_Color_Vertex_Locks,
	//IM_Show_Color_Vertex_Contrast_Locks,
	IM_Show_Color_Text_Locks,
	//IM_Show_Color_Text_Contrast_Locks,
	IM_Show_Color_Window_Locks,
	//IM_Show_Color_Window_Contrast_Locks,
	IM_Show_Color_Cut_Face_Locks,
	IM_Show_Color_Cut_Edge_Locks,
	IM_Show_Color_Locks,
	IM_Show_Visibility_Locks,
	IM_Show_Attribute_Locks,

	IM_Set_Color_Front_Locks,
	IM_Set_Color_Back_Locks,
	//IM_Set_Color_Face_Contrast_Locks,
	IM_Set_Color_Edge_Locks,
	//IM_Set_Color_Edge_Contrast_Locks,
	IM_Set_Color_Line_Locks,
	//IM_Set_Color_Line_Contrast_Locks,
	IM_Set_Color_Marker_Locks,
	//IM_Set_Color_Marker_Contrast_Locks,
	IM_Set_Color_Vertex_Locks,
	//IM_Set_Color_Vertex_Contrast_Locks,
	IM_Set_Color_Text_Locks,
	//IM_Set_Color_Text_Contrast_Locks,
	IM_Set_Color_Window_Locks,
	//IM_Set_Color_Window_Contrast_Locks,
	IM_Set_Color_Cut_Face_Locks,
	IM_Set_Color_Cut_Edge_Locks,
	IM_Set_Color_Locks,
	IM_Set_Visibility_Locks,
	IM_Set_Attribute_Locks,

	IM_Show_Face_Material_Diffuse_Color,

	IM_Copy_Segment_Info,
	IM_Free_Segment_Info,
	IM_Using_Analytic_HSRA,
	IM_Can_Snapshot,
	IM_Show_Full_Hard_Clip,
	IM_Show_Buffer_Size,
	IM_Using_Double_Buffer_Swap,

	IM_Get_Polyhedron_Points,
	IM_Get_Polyhedron_Point_Count,
	IM_Get_Polyhedron_Shell_Face_List,
	IM_Get_Polyhedron_Shell_Face_List_Length,
	IM_Polyhedron_Face_Normals_Valid,
	IM_Polyhedron_Generate_Face_List,
	IM_Polyhedron_Assemble_Face_Normals,
	IM_Get_Polyhedron_Face_Count,

	IM_Pack_RGBAS32,
	IM_Can_Save_And_Restore_Regions,
	IM_Key_To_Geometry_Pointer,
	IM_Get_Image_Block,

	IM_New_User_Shell,
	IM_Free_User_Shell,

	IM_ENSURE_ALPHA_TEST_ON,
	IM_ENSURE_ALPHA_TEST_OFF,

	/* driver calls */ 
	IM_Driver_Get_Window_Width,
	IM_Driver_Get_Window_Height,
	IM_Driver_Is_Double_Buffering,
	IM_Driver_Get_HDC,
	IM_Driver_Tristrip_Has_Valid_DL,
	IM_Driver_glActiveTextureARB,
	IM_Driver_ENSURE_TEXTURES_ON,
	IM_Driver_ENSURE_TEXTURES_OFF,
	IM_Driver_FORCE_TEXTURE_GEN_OFF,
	IM_Driver_Bind_Image_As_Texture,
	IM_Driver_Snapshot_Texture,
	IM_Driver_Snapshot_Depth_Texture,
	IM_Driver_Show_Projection_Matrix,
	IM_Driver_Draw_Clear_Window,
	IM_Driver_Get_Surface,	
    IM_Driver_Draw_Textured_Background,
    IM_Driver_Get_Graphics_Context,
	IM_Driver_Draw_DC_Image_Block_Z,
};


#define HIC_CALLS_DEFINED
#endif





