/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops.PMI.ZoneModifier;

public final class Type {
  public final static com.techsoft.hoops.PMI.ZoneModifier.Type None = new com.techsoft.hoops.PMI.ZoneModifier.Type("None");
  public final static com.techsoft.hoops.PMI.ZoneModifier.Type MaximumMaterialCondition = new com.techsoft.hoops.PMI.ZoneModifier.Type("MaximumMaterialCondition");
  public final static com.techsoft.hoops.PMI.ZoneModifier.Type LeastMaterialCondition = new com.techsoft.hoops.PMI.ZoneModifier.Type("LeastMaterialCondition");
  public final static com.techsoft.hoops.PMI.ZoneModifier.Type RegardlessOfFeatureSize = new com.techsoft.hoops.PMI.ZoneModifier.Type("RegardlessOfFeatureSize");
  public final static com.techsoft.hoops.PMI.ZoneModifier.Type TangentPlane = new com.techsoft.hoops.PMI.ZoneModifier.Type("TangentPlane");
  public final static com.techsoft.hoops.PMI.ZoneModifier.Type ProjectedToleranceZone = new com.techsoft.hoops.PMI.ZoneModifier.Type("ProjectedToleranceZone");
  public final static com.techsoft.hoops.PMI.ZoneModifier.Type FreeState = new com.techsoft.hoops.PMI.ZoneModifier.Type("FreeState");
  public final static com.techsoft.hoops.PMI.ZoneModifier.Type StatisticalTolerance = new com.techsoft.hoops.PMI.ZoneModifier.Type("StatisticalTolerance");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Type swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Type.class + " with value " + swigValue);
  }

  private Type(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Type(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Type(String swigName, Type swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Type[] swigValues = { None, MaximumMaterialCondition, LeastMaterialCondition, RegardlessOfFeatureSize, TangentPlane, ProjectedToleranceZone, FreeState, StatisticalTolerance };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

