/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

#if _M_X64
using HLONG = System.Int64;
using ID_Key = System.Int64;
#else
using HLONG = System.Int32;
using ID_Key = System.Int32;
#endif


public class IT_Index_Key_Extra : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public IT_Index_Key_Extra(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(IT_Index_Key_Extra obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~IT_Index_Key_Extra() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          HCSSTREAMPINVOKE.delete_IT_Index_Key_Extra(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public SWIGTYPE_p_a_2__int m_variants {
    set {
      HCSSTREAMPINVOKE.IT_Index_Key_Extra_m_variants_set(swigCPtr, SWIGTYPE_p_a_2__int.getCPtr(value));
    } 
    get {
      IntPtr cPtr = HCSSTREAMPINVOKE.IT_Index_Key_Extra_m_variants_get(swigCPtr);
      SWIGTYPE_p_a_2__int ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_a_2__int(cPtr, false);
      return ret;
    } 
  }

  public int m_options {
    set {
      HCSSTREAMPINVOKE.IT_Index_Key_Extra_m_options_set(swigCPtr, value);
    } 
    get {
      int ret = HCSSTREAMPINVOKE.IT_Index_Key_Extra_m_options_get(swigCPtr);
      return ret;
    } 
  }

  public IT_Index_Key_Extra() : this(HCSSTREAMPINVOKE.new_IT_Index_Key_Extra(), true) {
  }

}
