/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum TKO_Character_Attributes {
  TKO_Character_Name = 0x0001,
  TKO_Character_Size = 0x0002,
  TKO_Character_Vertical_Offset = 0x0004,
  TKO_Character_Omitted = 0x0008,
  TKO_Character_Invisible = 0x0010,
  TKO_Character_Slant = 0x0020,
  TKO_Character_Width_Scale = 0x0040,
  TKO_Character_Rotation = 0x0080,
  TKO_Character_Rotation_Fixed = 0x0100,
  TKO_Character_Horizontal_Offset = 0x0200,
  TKO_Character_Color = 0x0400,
  TKO_Character_Extended = 0x8000
}
