/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum TKO_Actions {
  TKO_Action_Type_Prune_Segment = 1,
  TKO_Action_Option_Segment_Tree = 0x0001
}
