/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum TKO_Font_Greeking_Modes {
  TKO_Font_Greeking_Mode_None = 0,
  TKO_Font_Greeking_Mode_Lines = 1,
  TKO_Font_Greeking_Mode_Box = 2
}
