/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops;

public class ColorPieceList {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public ColorPieceList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ColorPieceList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        HJMVOJNI.delete_ColorPieceList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ColorPieceList() {
    this(HJMVOJNI.new_ColorPieceList(), true);
  }

  public void AddColorPiece(int[] index, int len, int col) {
    HJMVOJNI.ColorPieceList_AddColorPiece(swigCPtr, this, index, len, col);
  }

  public ColorPiece FindMatch(int col, int ii, int ii2, int[] rpos, int[] rlen, boolean[] reverse) {
    long cPtr = HJMVOJNI.ColorPieceList_FindMatch(swigCPtr, this, col, ii, ii2, rpos, rlen, reverse);
    return (cPtr == 0) ? null : new ColorPiece(cPtr, false);
  }

  public void setM_ColorPieceList(SWIGTYPE_p_vlist_s value) {
    HJMVOJNI.ColorPieceList_m_ColorPieceList_set(swigCPtr, this, SWIGTYPE_p_vlist_s.getCPtr(value));
  }

  public SWIGTYPE_p_vlist_s getM_ColorPieceList() {
    long cPtr = HJMVOJNI.ColorPieceList_m_ColorPieceList_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_vlist_s(cPtr, false);
  }

}
