/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops;

public final class HFileIOResult {
  public final static HFileIOResult HIO_OK = new HFileIOResult("HIO_OK", HJMVOJNI.HIO_OK_get());
  public final static HFileIOResult HIO_VersionMismatch = new HFileIOResult("HIO_VersionMismatch", HJMVOJNI.HIO_VersionMismatch_get());
  public final static HFileIOResult HIO_Fail = new HFileIOResult("HIO_Fail", HJMVOJNI.HIO_Fail_get());
  public final static HFileIOResult HIO_NotHandled = new HFileIOResult("HIO_NotHandled", HJMVOJNI.HIO_NotHandled_get());
  public final static HFileIOResult HIO_BadFileName = new HFileIOResult("HIO_BadFileName", HJMVOJNI.HIO_BadFileName_get());
  public final static HFileIOResult HIO_BadOptions = new HFileIOResult("HIO_BadOptions", HJMVOJNI.HIO_BadOptions_get());
  public final static HFileIOResult HIO_BadLicense = new HFileIOResult("HIO_BadLicense", HJMVOJNI.HIO_BadLicense_get());
  public final static HFileIOResult HIO_LibraryNotFound = new HFileIOResult("HIO_LibraryNotFound", HJMVOJNI.HIO_LibraryNotFound_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static HFileIOResult swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + HFileIOResult.class + " with value " + swigValue);
  }

  private HFileIOResult(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private HFileIOResult(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private HFileIOResult(String swigName, HFileIOResult swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static HFileIOResult[] swigValues = { HIO_OK, HIO_VersionMismatch, HIO_Fail, HIO_NotHandled, HIO_BadFileName, HIO_BadOptions, HIO_BadLicense, HIO_LibraryNotFound };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

