/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops;

public class HIOManager {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public HIOManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(HIOManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        HJMVOJNI.delete_HIOManager(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public HIOManager() {
    this(HJMVOJNI.new_HIOManager(), true);
  }

  public HInputHandler RegisterInputHandler(String file_type, HInputHandler handler) {
    long cPtr = HJMVOJNI.HIOManager_RegisterInputHandler(swigCPtr, this, file_type, HInputHandler.getCPtr(handler), handler);
    return (cPtr == 0) ? null : new HInputHandler(cPtr, false);
  }

  public HOutputHandler RegisterOutputHandler(String file_type, HOutputHandler handler) {
    long cPtr = HJMVOJNI.HIOManager_RegisterOutputHandler(swigCPtr, this, file_type, HOutputHandler.getCPtr(handler), handler);
    return (cPtr == 0) ? null : new HOutputHandler(cPtr, false);
  }

  public HIOConnector RegisterConnector(String file_type, SWIGTYPE_p_f_p_void__p_void Create, SWIGTYPE_p_f_p_void__void Free) {
    long cPtr = HJMVOJNI.HIOManager_RegisterConnector(swigCPtr, this, file_type, SWIGTYPE_p_f_p_void__p_void.getCPtr(Create), SWIGTYPE_p_f_p_void__void.getCPtr(Free));
    return (cPtr == 0) ? null : new HIOConnector(cPtr, false);
  }

  public HInputHandler GetInputHandler(String file_type) {
    long cPtr = HJMVOJNI.HIOManager_GetInputHandler__SWIG_0(swigCPtr, this, file_type);
    return (cPtr == 0) ? null : new HInputHandler(cPtr, false);
  }

  public HInputHandler GetInputHandler(SWIGTYPE_p_wchar_t file_type) {
    long cPtr = HJMVOJNI.HIOManager_GetInputHandler__SWIG_1(swigCPtr, this, SWIGTYPE_p_wchar_t.getCPtr(file_type));
    return (cPtr == 0) ? null : new HInputHandler(cPtr, false);
  }

  public HOutputHandler GetOutputHandler(String file_type) {
    long cPtr = HJMVOJNI.HIOManager_GetOutputHandler__SWIG_0(swigCPtr, this, file_type);
    return (cPtr == 0) ? null : new HOutputHandler(cPtr, false);
  }

  public HOutputHandler GetOutputHandler(SWIGTYPE_p_wchar_t file_type) {
    long cPtr = HJMVOJNI.HIOManager_GetOutputHandler__SWIG_1(swigCPtr, this, SWIGTYPE_p_wchar_t.getCPtr(file_type));
    return (cPtr == 0) ? null : new HOutputHandler(cPtr, false);
  }

  public void RegisterHandlers() {
    HJMVOJNI.HIOManager_RegisterHandlers(swigCPtr, this);
  }

  public String GetInputHandlerTypes() {
    return HJMVOJNI.HIOManager_GetInputHandlerTypes(swigCPtr, this);
  }

  public String GetOutputHandlerTypes() {
    return HJMVOJNI.HIOManager_GetOutputHandlerTypes(swigCPtr, this);
  }

  public HIOConnector CreateConnector(String file_type) {
    long cPtr = HJMVOJNI.HIOManager_CreateConnector(swigCPtr, this, file_type);
    return (cPtr == 0) ? null : new HIOConnector(cPtr, false);
  }

  public void FreeConnector(HIOConnector old_connector) {
    HJMVOJNI.HIOManager_FreeConnector(swigCPtr, this, HIOConnector.getCPtr(old_connector), old_connector);
  }

  public static HIOManager GetCurrentHIOManager() {
    long cPtr = HJMVOJNI.HIOManager_GetCurrentHIOManager();
    return (cPtr == 0) ? null : new HIOManager(cPtr, false);
  }

  public static void GetFileOutputResultString(HFileIOResult result, StringBuffer result_str) {
    HJMVOJNI.HIOManager_GetFileOutputResultString(result.swigValue(), result_str);
  }

}
