/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops;

public class HKeyframe3String extends HKeyframe {
  private long swigCPtr;

  public HKeyframe3String(long cPtr, boolean cMemoryOwn) {
    super(HJMVOJNI.HKeyframe3String_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(HKeyframe3String obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        HJMVOJNI.delete_HKeyframe3String(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public HKeyframe3String() {
    this(HJMVOJNI.new_HKeyframe3String(), true);
  }

  public HKeyframe Clone() {
    long cPtr = HJMVOJNI.HKeyframe3String_Clone(swigCPtr, this);
    return (cPtr == 0) ? null : new HKeyframe(cPtr, false);
  }

  public void Serialize(SWIGTYPE_p_HUtilityXMLTag xmlgen) {
    HJMVOJNI.HKeyframe3String_Serialize(swigCPtr, this, SWIGTYPE_p_HUtilityXMLTag.getCPtr(xmlgen));
  }

  public void SetTarget(String t1, String t2, String t3) {
    HJMVOJNI.HKeyframe3String_SetTarget(swigCPtr, this, t1, t2, t3);
  }

  public StringBuffer GetTarget1() {
    return HJMVOJNI.HKeyframe3String_GetTarget1(swigCPtr, this);
  }

  public StringBuffer GetTarget2() {
    return HJMVOJNI.HKeyframe3String_GetTarget2(swigCPtr, this);
  }

  public StringBuffer GetTarget3() {
    return HJMVOJNI.HKeyframe3String_GetTarget3(swigCPtr, this);
  }

  public void setM_t1(String value) {
    HJMVOJNI.HKeyframe3String_m_t1_set(swigCPtr, this, value);
  }

  public String getM_t1() {
    return HJMVOJNI.HKeyframe3String_m_t1_get(swigCPtr, this);
  }

  public void setM_t2(String value) {
    HJMVOJNI.HKeyframe3String_m_t2_set(swigCPtr, this, value);
  }

  public String getM_t2() {
    return HJMVOJNI.HKeyframe3String_m_t2_get(swigCPtr, this);
  }

  public void setM_t3(String value) {
    HJMVOJNI.HKeyframe3String_m_t3_set(swigCPtr, this, value);
  }

  public String getM_t3() {
    return HJMVOJNI.HKeyframe3String_m_t3_get(swigCPtr, this);
  }

}
