/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops;

public class HKeyframeRotation extends HKeyframe {
  private long swigCPtr;

  public HKeyframeRotation(long cPtr, boolean cMemoryOwn) {
    super(HJMVOJNI.HKeyframeRotation_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(HKeyframeRotation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        HJMVOJNI.delete_HKeyframeRotation(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public HKeyframeRotation() {
    this(HJMVOJNI.new_HKeyframeRotation(), true);
  }

  public HKeyframe Clone() {
    long cPtr = HJMVOJNI.HKeyframeRotation_Clone(swigCPtr, this);
    return (cPtr == 0) ? null : new HKeyframe(cPtr, false);
  }

  public void setM_rotationtype(HANIRotationType value) {
    HJMVOJNI.HKeyframeRotation_m_rotationtype_set(swigCPtr, this, value.swigValue());
  }

  public HANIRotationType getM_rotationtype() {
    return HANIRotationType.swigToEnum(HJMVOJNI.HKeyframeRotation_m_rotationtype_get(swigCPtr, this));
  }

  public void setM_bLinear(boolean value) {
    HJMVOJNI.HKeyframeRotation_m_bLinear_set(swigCPtr, this, value);
  }

  public boolean getM_bLinear() {
    return HJMVOJNI.HKeyframeRotation_m_bLinear_get(swigCPtr, this);
  }

}
