/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops;

public class HLightsObject extends HObject {
  private long swigCPtr;

  public HLightsObject(long cPtr, boolean cMemoryOwn) {
    super(HJMVOJNI.HLightsObject_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(HLightsObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        HJMVOJNI.delete_HLightsObject(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public HLightsObject(HBaseView view) {
    this(HJMVOJNI.new_HLightsObject(HBaseView.getCPtr(view), view), true);
  }

  public static String GetStaticName() {
    return HJMVOJNI.HLightsObject_GetStaticName();
  }

  public String GetName() {
    return HJMVOJNI.HLightsObject_GetName(swigCPtr, this);
  }

  public int SetupHandlesEvent(HBaseView view, long key, boolean complex) {
    return HJMVOJNI.HLightsObject_SetupHandlesEvent(swigCPtr, this, HBaseView.getCPtr(view), view, key, complex);
  }

  public static void InsertLocalLight(HBaseView view, HPoint pos) {
    HJMVOJNI.HLightsObject_InsertLocalLight(HBaseView.getCPtr(view), view, HPoint.getCPtr(pos), pos);
  }

  public static void InsertDistantLight(HBaseView view, HPoint pos) {
    HJMVOJNI.HLightsObject_InsertDistantLight(HBaseView.getCPtr(view), view, HPoint.getCPtr(pos), pos);
  }

  public static void InsertSpotLight(HBaseView view, HPoint pos) {
    HJMVOJNI.HLightsObject_InsertSpotLight(HBaseView.getCPtr(view), view, HPoint.getCPtr(pos), pos);
  }

  public static void TurnLightsOnOff(HBaseView view, boolean onoff) {
    HJMVOJNI.HLightsObject_TurnLightsOnOff(HBaseView.getCPtr(view), view, onoff);
  }

}
