/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops;

public final class HLRMode {
  public final static HLRMode AnalyticHiddenLine = new HLRMode("AnalyticHiddenLine");
  public final static HLRMode FastHiddenLine = new HLRMode("FastHiddenLine");
  public final static HLRMode FakeHiddenLine = new HLRMode("FakeHiddenLine");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static HLRMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + HLRMode.class + " with value " + swigValue);
  }

  private HLRMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private HLRMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private HLRMode(String swigName, HLRMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static HLRMode[] swigValues = { AnalyticHiddenLine, FastHiddenLine, FakeHiddenLine };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

