/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops;

public class HMarkupManager {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public HMarkupManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(HMarkupManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        HJMVOJNI.delete_HMarkupManager(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    HJMVOJNI.HMarkupManager_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    HJMVOJNI.HMarkupManager_change_ownership(this, swigCPtr, true);
  }

  public HMarkupManager(HBaseView view) {
    this(HJMVOJNI.new_HMarkupManager(HBaseView.getCPtr(view), view), true);
    HJMVOJNI.HMarkupManager_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public void ReInit(HBaseView view) {
    HJMVOJNI.HMarkupManager_ReInit(swigCPtr, this, HBaseView.getCPtr(view), view);
  }

  public long OpenLayer(String layername, boolean setcamera, boolean emit_message) {return (getClass() == HMarkupManager.class) ? HJMVOJNI.HMarkupManager_OpenLayer__SWIG_0(swigCPtr, this, layername, setcamera, emit_message) : HJMVOJNI.HMarkupManager_OpenLayerSwigExplicitHMarkupManager__SWIG_0(swigCPtr, this, layername, setcamera, emit_message);}

  public long OpenLayer(String layername, boolean setcamera) {return (getClass() == HMarkupManager.class) ? HJMVOJNI.HMarkupManager_OpenLayer__SWIG_1(swigCPtr, this, layername, setcamera) : HJMVOJNI.HMarkupManager_OpenLayerSwigExplicitHMarkupManager__SWIG_1(swigCPtr, this, layername, setcamera);}

  public long OpenLayer(String layername) {return (getClass() == HMarkupManager.class) ? HJMVOJNI.HMarkupManager_OpenLayer__SWIG_2(swigCPtr, this, layername) : HJMVOJNI.HMarkupManager_OpenLayerSwigExplicitHMarkupManager__SWIG_2(swigCPtr, this, layername);}

  public long RenameLayer(long laykey, String new_name) {return (getClass() == HMarkupManager.class) ? HJMVOJNI.HMarkupManager_RenameLayer(swigCPtr, this, laykey, new_name) : HJMVOJNI.HMarkupManager_RenameLayerSwigExplicitHMarkupManager(swigCPtr, this, laykey, new_name);}

  public long CopyLayer(long laykey, String new_name) {return (getClass() == HMarkupManager.class) ? HJMVOJNI.HMarkupManager_CopyLayer(swigCPtr, this, laykey, new_name) : HJMVOJNI.HMarkupManager_CopyLayerSwigExplicitHMarkupManager(swigCPtr, this, laykey, new_name);}

  public boolean GetCamera(long layerkey, HCamera cam) {
    return (getClass() == HMarkupManager.class) ? HJMVOJNI.HMarkupManager_GetCamera(swigCPtr, this, layerkey, HCamera.getCPtr(cam), cam) : HJMVOJNI.HMarkupManager_GetCameraSwigExplicitHMarkupManager(swigCPtr, this, layerkey, HCamera.getCPtr(cam), cam);
  }

  public long OpenLayer(long layerkey, boolean setcamera) {return (getClass() == HMarkupManager.class) ? HJMVOJNI.HMarkupManager_OpenLayer__SWIG_3(swigCPtr, this, layerkey, setcamera) : HJMVOJNI.HMarkupManager_OpenLayerSwigExplicitHMarkupManager__SWIG_3(swigCPtr, this, layerkey, setcamera);}

  public long OpenLayer(long layerkey) {return (getClass() == HMarkupManager.class) ? HJMVOJNI.HMarkupManager_OpenLayer__SWIG_4(swigCPtr, this, layerkey) : HJMVOJNI.HMarkupManager_OpenLayerSwigExplicitHMarkupManager__SWIG_4(swigCPtr, this, layerkey);}

  public long FindLayer(String layername) {return (getClass() == HMarkupManager.class) ? HJMVOJNI.HMarkupManager_FindLayer(swigCPtr, this, layername) : HJMVOJNI.HMarkupManager_FindLayerSwigExplicitHMarkupManager(swigCPtr, this, layername);}

  public String GetLayerNames() {
    return (getClass() == HMarkupManager.class) ? HJMVOJNI.HMarkupManager_GetLayerNames(swigCPtr, this) : HJMVOJNI.HMarkupManager_GetLayerNamesSwigExplicitHMarkupManager(swigCPtr, this);
  }

  public long GetCurrentLayerKey() {return (getClass() == HMarkupManager.class) ? HJMVOJNI.HMarkupManager_GetCurrentLayerKey(swigCPtr, this) : HJMVOJNI.HMarkupManager_GetCurrentLayerKeySwigExplicitHMarkupManager(swigCPtr, this);}

  public String GetCurrentLayerName() {
    return (getClass() == HMarkupManager.class) ? HJMVOJNI.HMarkupManager_GetCurrentLayerName(swigCPtr, this) : HJMVOJNI.HMarkupManager_GetCurrentLayerNameSwigExplicitHMarkupManager(swigCPtr, this);
  }

  public void DisableCurrentLayer(boolean emit_message) {
    if (getClass() == HMarkupManager.class) HJMVOJNI.HMarkupManager_DisableCurrentLayer__SWIG_0(swigCPtr, this, emit_message); else HJMVOJNI.HMarkupManager_DisableCurrentLayerSwigExplicitHMarkupManager__SWIG_0(swigCPtr, this, emit_message);
  }

  public void DisableCurrentLayer() {
    if (getClass() == HMarkupManager.class) HJMVOJNI.HMarkupManager_DisableCurrentLayer__SWIG_1(swigCPtr, this); else HJMVOJNI.HMarkupManager_DisableCurrentLayerSwigExplicitHMarkupManager__SWIG_1(swigCPtr, this);
  }

  public void DeleteLayer(String layername) {
    if (getClass() == HMarkupManager.class) HJMVOJNI.HMarkupManager_DeleteLayer__SWIG_0(swigCPtr, this, layername); else HJMVOJNI.HMarkupManager_DeleteLayerSwigExplicitHMarkupManager__SWIG_0(swigCPtr, this, layername);
  }

  public void DeleteLayer(long layerkey) {
    if (getClass() == HMarkupManager.class) HJMVOJNI.HMarkupManager_DeleteLayer__SWIG_1(swigCPtr, this, layerkey); else HJMVOJNI.HMarkupManager_DeleteLayerSwigExplicitHMarkupManager__SWIG_1(swigCPtr, this, layerkey);
  }

  public void SetDefaultLayerKey(long layerkey) {
    HJMVOJNI.HMarkupManager_SetDefaultLayerKey(swigCPtr, this, layerkey);
  }

  public long GetDefaultLayerKey() {return HJMVOJNI.HMarkupManager_GetDefaultLayerKey(swigCPtr, this);}

  public long GetMarkupKey() {return HJMVOJNI.HMarkupManager_GetMarkupKey(swigCPtr, this);}

  public long GetMarkupLayerKey() {return HJMVOJNI.HMarkupManager_GetMarkupLayerKey(swigCPtr, this);}

  public float GetMarkupWeight() {
    return (getClass() == HMarkupManager.class) ? HJMVOJNI.HMarkupManager_GetMarkupWeight(swigCPtr, this) : HJMVOJNI.HMarkupManager_GetMarkupWeightSwigExplicitHMarkupManager(swigCPtr, this);
  }

  public void SetMarkupWeight(float weight) {
    if (getClass() == HMarkupManager.class) HJMVOJNI.HMarkupManager_SetMarkupWeight(swigCPtr, this, weight); else HJMVOJNI.HMarkupManager_SetMarkupWeightSwigExplicitHMarkupManager(swigCPtr, this, weight);
  }

  public void GetMarkupColor(HPoint markup_color) {
    if (getClass() == HMarkupManager.class) HJMVOJNI.HMarkupManager_GetMarkupColor(swigCPtr, this, HPoint.getCPtr(markup_color), markup_color); else HJMVOJNI.HMarkupManager_GetMarkupColorSwigExplicitHMarkupManager(swigCPtr, this, HPoint.getCPtr(markup_color), markup_color);
  }

  public void SetMarkupColor(HPoint markup_color) {
    if (getClass() == HMarkupManager.class) HJMVOJNI.HMarkupManager_SetMarkupColor(swigCPtr, this, HPoint.getCPtr(markup_color), markup_color); else HJMVOJNI.HMarkupManager_SetMarkupColorSwigExplicitHMarkupManager(swigCPtr, this, HPoint.getCPtr(markup_color), markup_color);
  }

  public void EmitMarkupSegment(long key) {
    if (getClass() == HMarkupManager.class) HJMVOJNI.HMarkupManager_EmitMarkupSegment(swigCPtr, this, key); else HJMVOJNI.HMarkupManager_EmitMarkupSegmentSwigExplicitHMarkupManager(swigCPtr, this, key);
  }

  public void InsertMarkupSegmentFromMessage(String in_data, int data_length) {
    if (getClass() == HMarkupManager.class) HJMVOJNI.HMarkupManager_InsertMarkupSegmentFromMessage(swigCPtr, this, in_data, data_length); else HJMVOJNI.HMarkupManager_InsertMarkupSegmentFromMessageSwigExplicitHMarkupManager(swigCPtr, this, in_data, data_length);
  }

  public void EmitDisableCurrentMarkupLayer() {
    if (getClass() == HMarkupManager.class) HJMVOJNI.HMarkupManager_EmitDisableCurrentMarkupLayer(swigCPtr, this); else HJMVOJNI.HMarkupManager_EmitDisableCurrentMarkupLayerSwigExplicitHMarkupManager(swigCPtr, this);
  }

  public void DisableCurrentMarkupLayerFromMessage(String data, int data_length) {
    if (getClass() == HMarkupManager.class) HJMVOJNI.HMarkupManager_DisableCurrentMarkupLayerFromMessage(swigCPtr, this, data, data_length); else HJMVOJNI.HMarkupManager_DisableCurrentMarkupLayerFromMessageSwigExplicitHMarkupManager(swigCPtr, this, data, data_length);
  }

  public void EmitSetMarkupLayer(String layer) {
    if (getClass() == HMarkupManager.class) HJMVOJNI.HMarkupManager_EmitSetMarkupLayer(swigCPtr, this, layer); else HJMVOJNI.HMarkupManager_EmitSetMarkupLayerSwigExplicitHMarkupManager(swigCPtr, this, layer);
  }

  public void SetMarkupLayerFromMessage(String data, int data_length) {
    if (getClass() == HMarkupManager.class) HJMVOJNI.HMarkupManager_SetMarkupLayerFromMessage(swigCPtr, this, data, data_length); else HJMVOJNI.HMarkupManager_SetMarkupLayerFromMessageSwigExplicitHMarkupManager(swigCPtr, this, data, data_length);
  }

  public boolean GetPreviewImage(String arg0, int[] arg1, int[] arg2, int[] arg3, SWIGTYPE_p_p_unsigned_char arg4) {
    return HJMVOJNI.HMarkupManager_GetPreviewImage(swigCPtr, this, arg0, arg1, arg2, arg3, SWIGTYPE_p_p_unsigned_char.getCPtr(arg4));
  }

  public void UpdatePreviewImage(boolean forceUpdate) {
    if (getClass() == HMarkupManager.class) HJMVOJNI.HMarkupManager_UpdatePreviewImage__SWIG_0(swigCPtr, this, forceUpdate); else HJMVOJNI.HMarkupManager_UpdatePreviewImageSwigExplicitHMarkupManager__SWIG_0(swigCPtr, this, forceUpdate);
  }

  public void UpdatePreviewImage() {
    if (getClass() == HMarkupManager.class) HJMVOJNI.HMarkupManager_UpdatePreviewImage__SWIG_1(swigCPtr, this); else HJMVOJNI.HMarkupManager_UpdatePreviewImageSwigExplicitHMarkupManager__SWIG_1(swigCPtr, this);
  }

  public boolean IsCameraLayer(long layerkey) {
    return HJMVOJNI.HMarkupManager_IsCameraLayer(swigCPtr, this, layerkey);
  }

  public void SetLayerCondition(long layerkey) {
    HJMVOJNI.HMarkupManager_SetLayerCondition(swigCPtr, this, layerkey);
  }

  public void UnsetCurrentLayerCondition() {
    HJMVOJNI.HMarkupManager_UnsetCurrentLayerCondition(swigCPtr, this);
  }

  public void UnsetLayerCondition(long layerkey) {
    HJMVOJNI.HMarkupManager_UnsetLayerCondition(swigCPtr, this, layerkey);
  }

  public void SetGeneratePreviewImage(boolean onoff) {
    HJMVOJNI.HMarkupManager_SetGeneratePreviewImage(swigCPtr, this, onoff);
  }

  public boolean GetGeneratePreviewImage() {
    return HJMVOJNI.HMarkupManager_GetGeneratePreviewImage(swigCPtr, this);
  }

  public void SetNoResetOnCameraChange() {
    HJMVOJNI.HMarkupManager_SetNoResetOnCameraChange(swigCPtr, this);
  }

  public boolean GetResetOnCameraChange(long layerkey) {
    return HJMVOJNI.HMarkupManager_GetResetOnCameraChange(swigCPtr, this, layerkey);
  }

  protected void SetupNewLayer() {
    if (getClass() == HMarkupManager.class) HJMVOJNI.HMarkupManager_SetupNewLayer(swigCPtr, this); else HJMVOJNI.HMarkupManager_SetupNewLayerSwigExplicitHMarkupManager(swigCPtr, this);
  }

  protected void OpenLayerInternal(long layerkey, boolean setcamera) {
    if (getClass() == HMarkupManager.class) HJMVOJNI.HMarkupManager_OpenLayerInternal(swigCPtr, this, layerkey, setcamera); else HJMVOJNI.HMarkupManager_OpenLayerInternalSwigExplicitHMarkupManager(swigCPtr, this, layerkey, setcamera);
  }

  protected void setM_pHView(HBaseView value) {
    HJMVOJNI.HMarkupManager_m_pHView_set(swigCPtr, this, HBaseView.getCPtr(value), value);
  }

  protected HBaseView getM_pHView() {
    long cPtr = HJMVOJNI.HMarkupManager_m_pHView_get(swigCPtr, this);
    return (cPtr == 0) ? null : new HBaseView(cPtr, false);
  }

  protected void setM_ActiveLayerKey(long value) {
    HJMVOJNI.HMarkupManager_m_ActiveLayerKey_set(swigCPtr, this, value);
  }

  protected long getM_ActiveLayerKey() {return HJMVOJNI.HMarkupManager_m_ActiveLayerKey_get(swigCPtr, this);}

  protected void setM_ActiveLayerName(StringBuffer value) {
    HJMVOJNI.HMarkupManager_m_ActiveLayerName_set(swigCPtr, this, value);
  }

  protected StringBuffer getM_ActiveLayerName() {
    return HJMVOJNI.HMarkupManager_m_ActiveLayerName_get(swigCPtr, this);
  }

  protected void setM_DefaultLayerKey(long value) {
    HJMVOJNI.HMarkupManager_m_DefaultLayerKey_set(swigCPtr, this, value);
  }

  protected long getM_DefaultLayerKey() {return HJMVOJNI.HMarkupManager_m_DefaultLayerKey_get(swigCPtr, this);}

  protected void setM_MarkupKey(long value) {
    HJMVOJNI.HMarkupManager_m_MarkupKey_set(swigCPtr, this, value);
  }

  protected long getM_MarkupKey() {return HJMVOJNI.HMarkupManager_m_MarkupKey_get(swigCPtr, this);}

  protected void setM_MarkupLayerKey(long value) {
    HJMVOJNI.HMarkupManager_m_MarkupLayerKey_set(swigCPtr, this, value);
  }

  protected long getM_MarkupLayerKey() {return HJMVOJNI.HMarkupManager_m_MarkupLayerKey_get(swigCPtr, this);}

  protected void setM_MarkupColor(HPoint value) {
    HJMVOJNI.HMarkupManager_m_MarkupColor_set(swigCPtr, this, HPoint.getCPtr(value), value);
  }

  protected HPoint getM_MarkupColor() {
    long cPtr = HJMVOJNI.HMarkupManager_m_MarkupColor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new HPoint(cPtr, false);
  }

  protected void setM_fMarkupWeight(float value) {
    HJMVOJNI.HMarkupManager_m_fMarkupWeight_set(swigCPtr, this, value);
  }

  protected float getM_fMarkupWeight() {
    return HJMVOJNI.HMarkupManager_m_fMarkupWeight_get(swigCPtr, this);
  }

  protected void setM_allNames(StringBuffer value) {
    HJMVOJNI.HMarkupManager_m_allNames_set(swigCPtr, this, value);
  }

  protected StringBuffer getM_allNames() {
    return HJMVOJNI.HMarkupManager_m_allNames_get(swigCPtr, this);
  }

  protected void setM_bGeneratePreviewImage(boolean value) {
    HJMVOJNI.HMarkupManager_m_bGeneratePreviewImage_set(swigCPtr, this, value);
  }

  protected boolean getM_bGeneratePreviewImage() {
    return HJMVOJNI.HMarkupManager_m_bGeneratePreviewImage_get(swigCPtr, this);
  }

}
