/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops;

public class HOpCreateSphere extends HOpConstructSphere {
  private long swigCPtr;

  public HOpCreateSphere(long cPtr, boolean cMemoryOwn) {
    super(HJMVOJNI.HOpCreateSphere_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(HOpCreateSphere obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        HJMVOJNI.delete_HOpCreateSphere(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    HJMVOJNI.HOpCreateSphere_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    HJMVOJNI.HOpCreateSphere_change_ownership(this, swigCPtr, true);
  }

  public HOpCreateSphere(HBaseView view, int DoRepeat, int DoCapture) {
    this(HJMVOJNI.new_HOpCreateSphere__SWIG_0(HBaseView.getCPtr(view), view, DoRepeat, DoCapture), true);
    HJMVOJNI.HOpCreateSphere_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public HOpCreateSphere(HBaseView view, int DoRepeat) {
    this(HJMVOJNI.new_HOpCreateSphere__SWIG_1(HBaseView.getCPtr(view), view, DoRepeat), true);
    HJMVOJNI.HOpCreateSphere_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public HOpCreateSphere(HBaseView view) {
    this(HJMVOJNI.new_HOpCreateSphere__SWIG_2(HBaseView.getCPtr(view), view), true);
    HJMVOJNI.HOpCreateSphere_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public String GetName() {
    return (getClass() == HOpCreateSphere.class) ? HJMVOJNI.HOpCreateSphere_GetName(swigCPtr, this) : HJMVOJNI.HOpCreateSphere_GetNameSwigExplicitHOpCreateSphere(swigCPtr, this);
  }

  public int OnLButtonUp(HEventInfo hevent) {
    return (getClass() == HOpCreateSphere.class) ? HJMVOJNI.HOpCreateSphere_OnLButtonUp(swigCPtr, this, HEventInfo.getCPtr(hevent), hevent) : HJMVOJNI.HOpCreateSphere_OnLButtonUpSwigExplicitHOpCreateSphere(swigCPtr, this, HEventInfo.getCPtr(hevent), hevent);
  }

  public HBaseOperator Clone() {
    long cPtr = (getClass() == HOpCreateSphere.class) ? HJMVOJNI.HOpCreateSphere_Clone(swigCPtr, this) : HJMVOJNI.HOpCreateSphere_CloneSwigExplicitHOpCreateSphere(swigCPtr, this);
    return (cPtr == 0) ? null : new HBaseOperator(cPtr, false);
  }

}
