/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops;

public class HOpConstructNurbsCurve extends HOpConstructPolyline {
  private long swigCPtr;

  public HOpConstructNurbsCurve(long cPtr, boolean cMemoryOwn) {
    super(HJMVOJNI.HOpConstructNurbsCurve_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(HOpConstructNurbsCurve obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        HJMVOJNI.delete_HOpConstructNurbsCurve(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    HJMVOJNI.HOpConstructNurbsCurve_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    HJMVOJNI.HOpConstructNurbsCurve_change_ownership(this, swigCPtr, true);
  }

  protected void setM_Degree(int value) {
    HJMVOJNI.HOpConstructNurbsCurve_m_Degree_set(swigCPtr, this, value);
  }

  protected int getM_Degree() {
    return HJMVOJNI.HOpConstructNurbsCurve_m_Degree_get(swigCPtr, this);
  }

  protected void setM_StartU(int value) {
    HJMVOJNI.HOpConstructNurbsCurve_m_StartU_set(swigCPtr, this, value);
  }

  protected int getM_StartU() {
    return HJMVOJNI.HOpConstructNurbsCurve_m_StartU_get(swigCPtr, this);
  }

  protected void setM_EndU(int value) {
    HJMVOJNI.HOpConstructNurbsCurve_m_EndU_set(swigCPtr, this, value);
  }

  protected int getM_EndU() {
    return HJMVOJNI.HOpConstructNurbsCurve_m_EndU_get(swigCPtr, this);
  }

  protected void setM_bFirstTimeThrough(boolean value) {
    HJMVOJNI.HOpConstructNurbsCurve_m_bFirstTimeThrough_set(swigCPtr, this, value);
  }

  protected boolean getM_bFirstTimeThrough() {
    return HJMVOJNI.HOpConstructNurbsCurve_m_bFirstTimeThrough_get(swigCPtr, this);
  }

  public HOpConstructNurbsCurve(HBaseView view, int DoRepeat, int DoCapture) {
    this(HJMVOJNI.new_HOpConstructNurbsCurve__SWIG_0(HBaseView.getCPtr(view), view, DoRepeat, DoCapture), true);
    HJMVOJNI.HOpConstructNurbsCurve_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public HOpConstructNurbsCurve(HBaseView view, int DoRepeat) {
    this(HJMVOJNI.new_HOpConstructNurbsCurve__SWIG_1(HBaseView.getCPtr(view), view, DoRepeat), true);
    HJMVOJNI.HOpConstructNurbsCurve_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public HOpConstructNurbsCurve(HBaseView view) {
    this(HJMVOJNI.new_HOpConstructNurbsCurve__SWIG_2(HBaseView.getCPtr(view), view), true);
    HJMVOJNI.HOpConstructNurbsCurve_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public HBaseOperator Clone() {
    long cPtr = (getClass() == HOpConstructNurbsCurve.class) ? HJMVOJNI.HOpConstructNurbsCurve_Clone(swigCPtr, this) : HJMVOJNI.HOpConstructNurbsCurve_CloneSwigExplicitHOpConstructNurbsCurve(swigCPtr, this);
    return (cPtr == 0) ? null : new HBaseOperator(cPtr, false);
  }

  public String GetName() {
    return (getClass() == HOpConstructNurbsCurve.class) ? HJMVOJNI.HOpConstructNurbsCurve_GetName(swigCPtr, this) : HJMVOJNI.HOpConstructNurbsCurve_GetNameSwigExplicitHOpConstructNurbsCurve(swigCPtr, this);
  }

  public int OnNoButtonDownAndMove(HEventInfo hevent) {
    return (getClass() == HOpConstructNurbsCurve.class) ? HJMVOJNI.HOpConstructNurbsCurve_OnNoButtonDownAndMove(swigCPtr, this, HEventInfo.getCPtr(hevent), hevent) : HJMVOJNI.HOpConstructNurbsCurve_OnNoButtonDownAndMoveSwigExplicitHOpConstructNurbsCurve(swigCPtr, this, HEventInfo.getCPtr(hevent), hevent);
  }

  public int OnLButtonDown(HEventInfo hevent) {
    return (getClass() == HOpConstructNurbsCurve.class) ? HJMVOJNI.HOpConstructNurbsCurve_OnLButtonDown(swigCPtr, this, HEventInfo.getCPtr(hevent), hevent) : HJMVOJNI.HOpConstructNurbsCurve_OnLButtonDownSwigExplicitHOpConstructNurbsCurve(swigCPtr, this, HEventInfo.getCPtr(hevent), hevent);
  }

  public int OnLButtonDblClk(HEventInfo hevent) {
    return (getClass() == HOpConstructNurbsCurve.class) ? HJMVOJNI.HOpConstructNurbsCurve_OnLButtonDblClk(swigCPtr, this, HEventInfo.getCPtr(hevent), hevent) : HJMVOJNI.HOpConstructNurbsCurve_OnLButtonDblClkSwigExplicitHOpConstructNurbsCurve(swigCPtr, this, HEventInfo.getCPtr(hevent), hevent);
  }

  public int OnMButtonDown(HEventInfo hevent) {
    return (getClass() == HOpConstructNurbsCurve.class) ? HJMVOJNI.HOpConstructNurbsCurve_OnMButtonDown(swigCPtr, this, HEventInfo.getCPtr(hevent), hevent) : HJMVOJNI.HOpConstructNurbsCurve_OnMButtonDownSwigExplicitHOpConstructNurbsCurve(swigCPtr, this, HEventInfo.getCPtr(hevent), hevent);
  }

}
