/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops;

public class HShellRegion {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public HShellRegion(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(HShellRegion obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        HJMVOJNI.delete_HShellRegion(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public HShellRegion(HShellObject pShell, int iRegionIndex) {
    this(HJMVOJNI.new_HShellRegion(HShellObject.getCPtr(pShell), pShell, iRegionIndex), true);
  }

  public int GetFaceCount() {
    return HJMVOJNI.HShellRegion_GetFaceCount(swigCPtr, this);
  }

  public HShellFace GetFace(int index) {
    return new HShellFace(HJMVOJNI.HShellRegion_GetFace(swigCPtr, this, index), true);
  }

}
