/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops;

public class HSmoothShadow extends HShadow {
  private long swigCPtr;

  public HSmoothShadow(long cPtr, boolean cMemoryOwn) {
    super(HJMVOJNI.HSmoothShadow_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(HSmoothShadow obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        HJMVOJNI.delete_HSmoothShadow(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public HSmoothShadow(long ModelSegmentKey, long ShadowBaseSegmentKey, boolean UseOglShadow) {
    this(HJMVOJNI.new_HSmoothShadow__SWIG_0(ModelSegmentKey, ShadowBaseSegmentKey, UseOglShadow), true);
  }

  public HSmoothShadow(long ModelSegmentKey, long ShadowBaseSegmentKey) {
    this(HJMVOJNI.new_HSmoothShadow__SWIG_1(ModelSegmentKey, ShadowBaseSegmentKey), true);
  }

  public void CleanUp() {
    HJMVOJNI.HSmoothShadow_CleanUp(swigCPtr, this);
  }

  public void Create(ShadowPlaneType ptype, int TextureSize, int FilterSize, int[] filter) {
    HJMVOJNI.HSmoothShadow_Create__SWIG_0(swigCPtr, this, ptype.swigValue(), TextureSize, FilterSize, filter);
  }

  public void Create(ShadowPlaneType ptype, int TextureSize, int FilterSize) {
    HJMVOJNI.HSmoothShadow_Create__SWIG_1(swigCPtr, this, ptype.swigValue(), TextureSize, FilterSize);
  }

  public void Create(ShadowPlaneType ptype, int TextureSize) {
    HJMVOJNI.HSmoothShadow_Create__SWIG_2(swigCPtr, this, ptype.swigValue(), TextureSize);
  }

  public void Create(ShadowPlaneType ptype) {
    HJMVOJNI.HSmoothShadow_Create__SWIG_3(swigCPtr, this, ptype.swigValue());
  }

  public void Create() {
    HJMVOJNI.HSmoothShadow_Create__SWIG_4(swigCPtr, this);
  }

  public int GetFilterSize() {
    return HJMVOJNI.HSmoothShadow_GetFilterSize(swigCPtr, this);
  }

  public int GetTextureSize() {
    return HJMVOJNI.HSmoothShadow_GetTextureSize(swigCPtr, this);
  }

  public void SetTextureSize(int TextureSize) {
    HJMVOJNI.HSmoothShadow_SetTextureSize(swigCPtr, this, TextureSize);
  }

  public void SetFilter(int[] filter, int FilterSize) {
    HJMVOJNI.HSmoothShadow_SetFilter(swigCPtr, this, filter, FilterSize);
  }

  public void UnDefineShadowTexture() {
    HJMVOJNI.HSmoothShadow_UnDefineShadowTexture(swigCPtr, this);
  }

  public static void UnDefineAllShadowTextures(long modelsegmentkey) {
    HJMVOJNI.HSmoothShadow_UnDefineAllShadowTextures(modelsegmentkey);
  }

  public void SetAllowOpenglShadow(boolean AllowOpenglShadow) {
    HJMVOJNI.HSmoothShadow_SetAllowOpenglShadow(swigCPtr, this, AllowOpenglShadow);
  }

}
