/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops;

public class HUndoItemCamera extends HUndoItem {
  private long swigCPtr;

  public HUndoItemCamera(long cPtr, boolean cMemoryOwn) {
    super(HJMVOJNI.HUndoItemCamera_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(HUndoItemCamera obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        HJMVOJNI.delete_HUndoItemCamera(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public HUndoItemCamera(HBaseView view) {
    this(HJMVOJNI.new_HUndoItemCamera(HBaseView.getCPtr(view), view), true);
  }

  public void Undo(boolean setupOnly) {
    HJMVOJNI.HUndoItemCamera_Undo__SWIG_0(swigCPtr, this, setupOnly);
  }

  public void Undo() {
    HJMVOJNI.HUndoItemCamera_Undo__SWIG_1(swigCPtr, this);
  }

  public void Redo(boolean setupOnly) {
    HJMVOJNI.HUndoItemCamera_Redo__SWIG_0(swigCPtr, this, setupOnly);
  }

  public void Redo() {
    HJMVOJNI.HUndoItemCamera_Redo__SWIG_1(swigCPtr, this);
  }

  public HCamera GetCamera() {
    long cPtr = HJMVOJNI.HUndoItemCamera_GetCamera(swigCPtr, this);
    return (cPtr == 0) ? null : new HCamera(cPtr, false);
  }

  public String GetName() {
    return HJMVOJNI.HUndoItemCamera_GetName(swigCPtr, this);
  }

}
