/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops;
import com.techsoft.hoops.*;
public class Orientation {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Orientation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Orientation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        HJMVOJNI.delete_Orientation(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Orientation() {
    this(HJMVOJNI.new_Orientation__SWIG_0(), true);
  }

  public Orientation(Orientation that) {
    this(HJMVOJNI.new_Orientation__SWIG_1(Orientation.getCPtr(that), that), true);
  }

  public void Set(Orientation that) {
    HJMVOJNI.Orientation_Set(swigCPtr, this, Orientation.getCPtr(that), that);
  }

  public void GetXComponent(HPoint out_component) {
    HJMVOJNI.Orientation_GetXComponent__SWIG_0(swigCPtr, this, HPoint.getCPtr(out_component), out_component);
  }

  public void GetXComponent(float[] out_x, float[] out_y, float[] out_z) {
    HJMVOJNI.Orientation_GetXComponent__SWIG_1(swigCPtr, this, out_x, out_y, out_z);
  }

  public void SetXComponent(HPoint in_component) {
    HJMVOJNI.Orientation_SetXComponent__SWIG_0(swigCPtr, this, HPoint.getCPtr(in_component), in_component);
  }

  public void SetXComponent(float in_x, float in_y, float in_z) {
    HJMVOJNI.Orientation_SetXComponent__SWIG_1(swigCPtr, this, in_x, in_y, in_z);
  }

  public void GetYComponent(HPoint out_component) {
    HJMVOJNI.Orientation_GetYComponent__SWIG_0(swigCPtr, this, HPoint.getCPtr(out_component), out_component);
  }

  public void GetYComponent(float[] out_x, float[] out_y, float[] out_z) {
    HJMVOJNI.Orientation_GetYComponent__SWIG_1(swigCPtr, this, out_x, out_y, out_z);
  }

  public void SetYComponent(HPoint in_component) {
    HJMVOJNI.Orientation_SetYComponent__SWIG_0(swigCPtr, this, HPoint.getCPtr(in_component), in_component);
  }

  public void SetYComponent(float in_x, float in_y, float in_z) {
    HJMVOJNI.Orientation_SetYComponent__SWIG_1(swigCPtr, this, in_x, in_y, in_z);
  }

  public void GetZComponent(HPoint out_component) {
    HJMVOJNI.Orientation_GetZComponent__SWIG_0(swigCPtr, this, HPoint.getCPtr(out_component), out_component);
  }

  public void GetZComponent(float[] out_x, float[] out_y, float[] out_z) {
    HJMVOJNI.Orientation_GetZComponent__SWIG_1(swigCPtr, this, out_x, out_y, out_z);
  }

  public void SetZComponent(HPoint in_component) {
    HJMVOJNI.Orientation_SetZComponent__SWIG_0(swigCPtr, this, HPoint.getCPtr(in_component), in_component);
  }

  public void SetZComponent(float in_x, float in_y, float in_z) {
    HJMVOJNI.Orientation_SetZComponent__SWIG_1(swigCPtr, this, in_x, in_y, in_z);
  }

  public void GetOriginComponent(HPoint out_component) {
    HJMVOJNI.Orientation_GetOriginComponent__SWIG_0(swigCPtr, this, HPoint.getCPtr(out_component), out_component);
  }

  public void GetOriginComponent(float[] out_x, float[] out_y, float[] out_z) {
    HJMVOJNI.Orientation_GetOriginComponent__SWIG_1(swigCPtr, this, out_x, out_y, out_z);
  }

  public void SetOriginComponent(HPoint in_component) {
    HJMVOJNI.Orientation_SetOriginComponent__SWIG_0(swigCPtr, this, HPoint.getCPtr(in_component), in_component);
  }

  public void SetOriginComponent(float in_x, float in_y, float in_z) {
    HJMVOJNI.Orientation_SetOriginComponent__SWIG_1(swigCPtr, this, in_x, in_y, in_z);
  }

  public void GetMatrix(float[] out_matrix) {
    HJMVOJNI.Orientation_GetMatrix(swigCPtr, this, out_matrix);
  }

  public void SetMatrix(float[] in_matrix) {
    HJMVOJNI.Orientation_SetMatrix(swigCPtr, this, in_matrix);
  }

}
