/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

#if _M_X64
using MVO_POINTER_SIZED_INT = System.Int64;
using MVO_POINTER_SIZED_UINT = System.UInt64;
using ID_Key = System.Int64;
#else
using MVO_POINTER_SIZED_INT = System.Int32;
using MVO_POINTER_SIZED_UINT = System.UInt32;
using ID_Key = System.Int32;
#endif


public class HEventListenerManager : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public HEventListenerManager(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(HEventListenerManager obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }
  
  public void owns_memory(bool ownMemory) {
	swigCMemOwn = ownMemory;
  }

  ~HEventListenerManager() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          HCSMVOPINVOKE.delete_HEventListenerManager(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public HEventListenerManager() : this(HCSMVOPINVOKE.new_HEventListenerManager(), true) {
  }

  public void AddEventListener(HEventListener eventlistener, int priority) {
    HCSMVOPINVOKE.HEventListenerManager_AddEventListener(swigCPtr, HEventListener.getCPtr(eventlistener), priority);
  }

  public void Reset() {
    HCSMVOPINVOKE.HEventListenerManager_Reset(swigCPtr);
  }

  public void StartQuery() {
    HCSMVOPINVOKE.HEventListenerManager_StartQuery(swigCPtr);
  }

  public HEventListener GetEventListener() {
    IntPtr cPtr = HCSMVOPINVOKE.HEventListenerManager_GetEventListener(swigCPtr);
    HEventListener ret = (cPtr == IntPtr.Zero) ? null : new HEventListener(cPtr, false);
    return ret;
  }

  public bool RemoveEventListener(HEventListener eventlistener) {
    bool ret = HCSMVOPINVOKE.HEventListenerManager_RemoveEventListener(swigCPtr, HEventListener.getCPtr(eventlistener));
    return ret;
  }

}
