/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

#if _M_X64
using MVO_POINTER_SIZED_INT = System.Int64;
using MVO_POINTER_SIZED_UINT = System.UInt64;
using ID_Key = System.Int64;
#else
using MVO_POINTER_SIZED_INT = System.Int32;
using MVO_POINTER_SIZED_UINT = System.UInt32;
using ID_Key = System.Int32;
#endif


public class HGraphDataSetNode : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public HGraphDataSetNode(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(HGraphDataSetNode obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }
  
  public void owns_memory(bool ownMemory) {
	swigCMemOwn = ownMemory;
  }

  ~HGraphDataSetNode() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          HCSMVOPINVOKE.delete_HGraphDataSetNode(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public double bar_width {
    set {
      HCSMVOPINVOKE.HGraphDataSetNode_bar_width_set(swigCPtr, value);
    } 
    get {
      double ret = HCSMVOPINVOKE.HGraphDataSetNode_bar_width_get(swigCPtr);
      return ret;
    } 
  }

  public MVO_POINTER_SIZED_INT segment {
	set { HCSMVOPINVOKE.HGraphDataSetNode_segment_set(swigCPtr, value); } 
	get { return HCSMVOPINVOKE.HGraphDataSetNode_segment_get(swigCPtr); } 
  }

  public int data_size {
    set {
      HCSMVOPINVOKE.HGraphDataSetNode_data_size_set(swigCPtr, value);
    } 
    get {
      int ret = HCSMVOPINVOKE.HGraphDataSetNode_data_size_get(swigCPtr);
      return ret;
    } 
  }

  public HGraphPointFormat format {
    set {
      HCSMVOPINVOKE.HGraphDataSetNode_format_set(swigCPtr, (int)value);
    } 
    get {
      HGraphPointFormat ret = (HGraphPointFormat)HCSMVOPINVOKE.HGraphDataSetNode_format_get(swigCPtr);
      return ret;
    } 
  }

  public bool line_vis {
    set {
      HCSMVOPINVOKE.HGraphDataSetNode_line_vis_set(swigCPtr, value);
    } 
    get {
      bool ret = HCSMVOPINVOKE.HGraphDataSetNode_line_vis_get(swigCPtr);
      return ret;
    } 
  }

  public bool bar_vis {
    set {
      HCSMVOPINVOKE.HGraphDataSetNode_bar_vis_set(swigCPtr, value);
    } 
    get {
      bool ret = HCSMVOPINVOKE.HGraphDataSetNode_bar_vis_get(swigCPtr);
      return ret;
    } 
  }

  public bool polygon_vis {
    set {
      HCSMVOPINVOKE.HGraphDataSetNode_polygon_vis_set(swigCPtr, value);
    } 
    get {
      bool ret = HCSMVOPINVOKE.HGraphDataSetNode_polygon_vis_get(swigCPtr);
      return ret;
    } 
  }

  public HGraphDataSetNode() : this(HCSMVOPINVOKE.new_HGraphDataSetNode(), true) {
  }

}
