/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

#if _M_X64
using MVO_POINTER_SIZED_INT = System.Int64;
using MVO_POINTER_SIZED_UINT = System.UInt64;
using ID_Key = System.Int64;
#else
using MVO_POINTER_SIZED_INT = System.Int32;
using MVO_POINTER_SIZED_UINT = System.UInt32;
using ID_Key = System.Int32;
#endif


public class HIntRectangle : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public HIntRectangle(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(HIntRectangle obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }
  
  public void owns_memory(bool ownMemory) {
	swigCMemOwn = ownMemory;
  }

  ~HIntRectangle() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          HCSMVOPINVOKE.delete_HIntRectangle(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int left {
    set {
      HCSMVOPINVOKE.HIntRectangle_left_set(swigCPtr, value);
    } 
    get {
      int ret = HCSMVOPINVOKE.HIntRectangle_left_get(swigCPtr);
      return ret;
    } 
  }

  public int right {
    set {
      HCSMVOPINVOKE.HIntRectangle_right_set(swigCPtr, value);
    } 
    get {
      int ret = HCSMVOPINVOKE.HIntRectangle_right_get(swigCPtr);
      return ret;
    } 
  }

  public int bottom {
    set {
      HCSMVOPINVOKE.HIntRectangle_bottom_set(swigCPtr, value);
    } 
    get {
      int ret = HCSMVOPINVOKE.HIntRectangle_bottom_get(swigCPtr);
      return ret;
    } 
  }

  public int top {
    set {
      HCSMVOPINVOKE.HIntRectangle_top_set(swigCPtr, value);
    } 
    get {
      int ret = HCSMVOPINVOKE.HIntRectangle_top_get(swigCPtr);
      return ret;
    } 
  }

  public HIntRectangle() : this(HCSMVOPINVOKE.new_HIntRectangle(), true) {
  }

}
