/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

#if _M_X64
using MVO_POINTER_SIZED_INT = System.Int64;
using MVO_POINTER_SIZED_UINT = System.UInt64;
using ID_Key = System.Int64;
#else
using MVO_POINTER_SIZED_INT = System.Int32;
using MVO_POINTER_SIZED_UINT = System.UInt32;
using ID_Key = System.Int32;
#endif


public class HOpConstructRectangle : HBaseOperator {
  private HandleRef swigCPtr;

  public HOpConstructRectangle(IntPtr cPtr, bool cMemoryOwn) : base(HCSMVOPINVOKE.HOpConstructRectangleUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(HOpConstructRectangle obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~HOpConstructRectangle() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          HCSMVOPINVOKE.delete_HOpConstructRectangle(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public HOpConstructRectangle(HBaseView view, int DoRepeat, int DoCapture, bool UseCenterMarker) : this(HCSMVOPINVOKE.new_HOpConstructRectangle__SWIG_0(HBaseView.getCPtr(view), DoRepeat, DoCapture, UseCenterMarker), true) {
    SwigDirectorConnect();
  }

  public HOpConstructRectangle(HBaseView view, int DoRepeat, int DoCapture) : this(HCSMVOPINVOKE.new_HOpConstructRectangle__SWIG_1(HBaseView.getCPtr(view), DoRepeat, DoCapture), true) {
    SwigDirectorConnect();
  }

  public HOpConstructRectangle(HBaseView view, int DoRepeat) : this(HCSMVOPINVOKE.new_HOpConstructRectangle__SWIG_2(HBaseView.getCPtr(view), DoRepeat), true) {
    SwigDirectorConnect();
  }

  public HOpConstructRectangle(HBaseView view) : this(HCSMVOPINVOKE.new_HOpConstructRectangle__SWIG_3(HBaseView.getCPtr(view)), true) {
    SwigDirectorConnect();
  }

  public override string GetName() {
    string ret = ((this.GetType() == typeof(HOpConstructRectangle)) ? HCSMVOPINVOKE.HOpConstructRectangle_GetName(swigCPtr) : HCSMVOPINVOKE.HOpConstructRectangle_GetNameSwigExplicitHOpConstructRectangle(swigCPtr));
    return ret;
  }

  public override HBaseOperator Clone() {
    IntPtr cPtr = ((this.GetType() == typeof(HOpConstructRectangle)) ? HCSMVOPINVOKE.HOpConstructRectangle_Clone(swigCPtr) : HCSMVOPINVOKE.HOpConstructRectangle_CloneSwigExplicitHOpConstructRectangle(swigCPtr));
    HBaseOperator ret = (cPtr == IntPtr.Zero) ? null : new HBaseOperator(cPtr, false);
    return ret;
  }

  public override int OnLButtonDown(HEventInfo hevent) {
    int ret = ((this.GetType() == typeof(HOpConstructRectangle)) ? HCSMVOPINVOKE.HOpConstructRectangle_OnLButtonDown(swigCPtr, HEventInfo.getCPtr(hevent)) : HCSMVOPINVOKE.HOpConstructRectangle_OnLButtonDownSwigExplicitHOpConstructRectangle(swigCPtr, HEventInfo.getCPtr(hevent)));
    if (HCSMVOPINVOKE.SWIGPendingException.Pending) throw HCSMVOPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override int OnLButtonDownAndMove(HEventInfo hevent) {
    int ret = ((this.GetType() == typeof(HOpConstructRectangle)) ? HCSMVOPINVOKE.HOpConstructRectangle_OnLButtonDownAndMove(swigCPtr, HEventInfo.getCPtr(hevent)) : HCSMVOPINVOKE.HOpConstructRectangle_OnLButtonDownAndMoveSwigExplicitHOpConstructRectangle(swigCPtr, HEventInfo.getCPtr(hevent)));
    if (HCSMVOPINVOKE.SWIGPendingException.Pending) throw HCSMVOPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override int OnLButtonUp(HEventInfo hevent) {
    int ret = ((this.GetType() == typeof(HOpConstructRectangle)) ? HCSMVOPINVOKE.HOpConstructRectangle_OnLButtonUp(swigCPtr, HEventInfo.getCPtr(hevent)) : HCSMVOPINVOKE.HOpConstructRectangle_OnLButtonUpSwigExplicitHOpConstructRectangle(swigCPtr, HEventInfo.getCPtr(hevent)));
    if (HCSMVOPINVOKE.SWIGPendingException.Pending) throw HCSMVOPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override int OnRButtonUp(HEventInfo hevent) {
    int ret = ((this.GetType() == typeof(HOpConstructRectangle)) ? HCSMVOPINVOKE.HOpConstructRectangle_OnRButtonUp(swigCPtr, HEventInfo.getCPtr(hevent)) : HCSMVOPINVOKE.HOpConstructRectangle_OnRButtonUpSwigExplicitHOpConstructRectangle(swigCPtr, HEventInfo.getCPtr(hevent)));
    if (HCSMVOPINVOKE.SWIGPendingException.Pending) throw HCSMVOPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  protected bool m_bRectangleExists {
    set {
      HCSMVOPINVOKE.HOpConstructRectangle_m_bRectangleExists_set(swigCPtr, value);
    } 
    get {
      bool ret = HCSMVOPINVOKE.HOpConstructRectangle_m_bRectangleExists_get(swigCPtr);
      return ret;
    } 
  }

  protected HPoint m_ptRectangle {
    set {
      HCSMVOPINVOKE.HOpConstructRectangle_m_ptRectangle_set(swigCPtr, HPoint.getCPtr(value));
    } 
    get {
      IntPtr cPtr = HCSMVOPINVOKE.HOpConstructRectangle_m_ptRectangle_get(swigCPtr);
      HPoint ret = (cPtr == IntPtr.Zero) ? null : new HPoint(cPtr, false);
      return ret;
    } 
  }

  protected string m_pSavedVisibility {
    set {
      HCSMVOPINVOKE.HOpConstructRectangle_m_pSavedVisibility_set(swigCPtr, value);
    } 
    get {
      string ret = HCSMVOPINVOKE.HOpConstructRectangle_m_pSavedVisibility_get(swigCPtr);
      return ret;
    } 
  }

  protected string m_pSavedColor {
    set {
      HCSMVOPINVOKE.HOpConstructRectangle_m_pSavedColor_set(swigCPtr, value);
    } 
    get {
      string ret = HCSMVOPINVOKE.HOpConstructRectangle_m_pSavedColor_get(swigCPtr);
      return ret;
    } 
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("CreateListenerManager", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateHOpConstructRectangle_0(SwigDirectorCreateListenerManager);
    if (SwigDerivedClassHasMethod("OnLButtonDown", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateHOpConstructRectangle_1(SwigDirectorOnLButtonDown);
    if (SwigDerivedClassHasMethod("OnMouseMove", swigMethodTypes2))
      swigDelegate2 = new SwigDelegateHOpConstructRectangle_2(SwigDirectorOnMouseMove);
    if (SwigDerivedClassHasMethod("OnLButtonUp", swigMethodTypes3))
      swigDelegate3 = new SwigDelegateHOpConstructRectangle_3(SwigDirectorOnLButtonUp);
    if (SwigDerivedClassHasMethod("OnLButtonDblClk", swigMethodTypes4))
      swigDelegate4 = new SwigDelegateHOpConstructRectangle_4(SwigDirectorOnLButtonDblClk);
    if (SwigDerivedClassHasMethod("OnMButtonDown", swigMethodTypes5))
      swigDelegate5 = new SwigDelegateHOpConstructRectangle_5(SwigDirectorOnMButtonDown);
    if (SwigDerivedClassHasMethod("OnMButtonUp", swigMethodTypes6))
      swigDelegate6 = new SwigDelegateHOpConstructRectangle_6(SwigDirectorOnMButtonUp);
    if (SwigDerivedClassHasMethod("OnMButtonDblClk", swigMethodTypes7))
      swigDelegate7 = new SwigDelegateHOpConstructRectangle_7(SwigDirectorOnMButtonDblClk);
    if (SwigDerivedClassHasMethod("OnRButtonDown", swigMethodTypes8))
      swigDelegate8 = new SwigDelegateHOpConstructRectangle_8(SwigDirectorOnRButtonDown);
    if (SwigDerivedClassHasMethod("OnRButtonUp", swigMethodTypes9))
      swigDelegate9 = new SwigDelegateHOpConstructRectangle_9(SwigDirectorOnRButtonUp);
    if (SwigDerivedClassHasMethod("OnRButtonDblClk", swigMethodTypes10))
      swigDelegate10 = new SwigDelegateHOpConstructRectangle_10(SwigDirectorOnRButtonDblClk);
    if (SwigDerivedClassHasMethod("OnMouseWheel", swigMethodTypes11))
      swigDelegate11 = new SwigDelegateHOpConstructRectangle_11(SwigDirectorOnMouseWheel);
    if (SwigDerivedClassHasMethod("OnKeyDown", swigMethodTypes12))
      swigDelegate12 = new SwigDelegateHOpConstructRectangle_12(SwigDirectorOnKeyDown);
    if (SwigDerivedClassHasMethod("OnKeyUp", swigMethodTypes13))
      swigDelegate13 = new SwigDelegateHOpConstructRectangle_13(SwigDirectorOnKeyUp);
    if (SwigDerivedClassHasMethod("OnTouchesDown", swigMethodTypes14))
      swigDelegate14 = new SwigDelegateHOpConstructRectangle_14(SwigDirectorOnTouchesDown);
    if (SwigDerivedClassHasMethod("OnTouchesMove", swigMethodTypes15))
      swigDelegate15 = new SwigDelegateHOpConstructRectangle_15(SwigDirectorOnTouchesMove);
    if (SwigDerivedClassHasMethod("OnTouchesUp", swigMethodTypes16))
      swigDelegate16 = new SwigDelegateHOpConstructRectangle_16(SwigDirectorOnTouchesUp);
    if (SwigDerivedClassHasMethod("Clone", swigMethodTypes17))
      swigDelegate17 = new SwigDelegateHOpConstructRectangle_17(SwigDirectorClone);
    if (SwigDerivedClassHasMethod("OperatorStarted", swigMethodTypes18))
      swigDelegate18 = new SwigDelegateHOpConstructRectangle_18(SwigDirectorOperatorStarted);
    if (SwigDerivedClassHasMethod("GetName", swigMethodTypes19))
      swigDelegate19 = new SwigDelegateHOpConstructRectangle_19(SwigDirectorGetName);
    if (SwigDerivedClassHasMethod("OnLButtonDownAndMove", swigMethodTypes20))
      swigDelegate20 = new SwigDelegateHOpConstructRectangle_20(SwigDirectorOnLButtonDownAndMove);
    if (SwigDerivedClassHasMethod("OnMButtonDownAndMove", swigMethodTypes21))
      swigDelegate21 = new SwigDelegateHOpConstructRectangle_21(SwigDirectorOnMButtonDownAndMove);
    if (SwigDerivedClassHasMethod("OnRButtonDownAndMove", swigMethodTypes22))
      swigDelegate22 = new SwigDelegateHOpConstructRectangle_22(SwigDirectorOnRButtonDownAndMove);
    if (SwigDerivedClassHasMethod("OnLRButtonDownAndMove", swigMethodTypes23))
      swigDelegate23 = new SwigDelegateHOpConstructRectangle_23(SwigDirectorOnLRButtonDownAndMove);
    if (SwigDerivedClassHasMethod("OnNoButtonDownAndMove", swigMethodTypes24))
      swigDelegate24 = new SwigDelegateHOpConstructRectangle_24(SwigDirectorOnNoButtonDownAndMove);
    if (SwigDerivedClassHasMethod("OnTimer", swigMethodTypes25))
      swigDelegate25 = new SwigDelegateHOpConstructRectangle_25(SwigDirectorOnTimer);
    HCSMVOPINVOKE.HOpConstructRectangle_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2, swigDelegate3, swigDelegate4, swigDelegate5, swigDelegate6, swigDelegate7, swigDelegate8, swigDelegate9, swigDelegate10, swigDelegate11, swigDelegate12, swigDelegate13, swigDelegate14, swigDelegate15, swigDelegate16, swigDelegate17, swigDelegate18, swigDelegate19, swigDelegate20, swigDelegate21, swigDelegate22, swigDelegate23, swigDelegate24, swigDelegate25);
  }

  private bool SwigDerivedClassHasMethod(string methodName, Type[] methodTypes) {
    System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(HOpConstructRectangle));
    return hasDerivedMethod;
  }

  private IntPtr SwigDirectorCreateListenerManager() {
    return HEventListener.getCPtr(CreateListenerManager()).Handle;
  }

  private int SwigDirectorOnLButtonDown(IntPtr hevent) {
    return OnLButtonDown(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnMouseMove(IntPtr hevent) {
    return OnMouseMove(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnLButtonUp(IntPtr hevent) {
    return OnLButtonUp(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnLButtonDblClk(IntPtr hevent) {
    return OnLButtonDblClk(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnMButtonDown(IntPtr hevent) {
    return OnMButtonDown(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnMButtonUp(IntPtr hevent) {
    return OnMButtonUp(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnMButtonDblClk(IntPtr hevent) {
    return OnMButtonDblClk(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnRButtonDown(IntPtr hevent) {
    return OnRButtonDown(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnRButtonUp(IntPtr hevent) {
    return OnRButtonUp(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnRButtonDblClk(IntPtr hevent) {
    return OnRButtonDblClk(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnMouseWheel(IntPtr hevent) {
    return OnMouseWheel(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnKeyDown(IntPtr hevent) {
    return OnKeyDown(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnKeyUp(IntPtr hevent) {
    return OnKeyUp(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnTouchesDown(IntPtr hevent) {
    return OnTouchesDown(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnTouchesMove(IntPtr hevent) {
    return OnTouchesMove(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnTouchesUp(IntPtr hevent) {
    return OnTouchesUp(new HEventInfo(hevent, false));
  }

  private IntPtr SwigDirectorClone() {
    return HBaseOperator.getCPtr(Clone()).Handle;
  }

  private bool SwigDirectorOperatorStarted() {
    return OperatorStarted();
  }

  private string SwigDirectorGetName() {
    return GetName();
  }

  private int SwigDirectorOnLButtonDownAndMove(IntPtr hevent) {
    return OnLButtonDownAndMove(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnMButtonDownAndMove(IntPtr hevent) {
    return OnMButtonDownAndMove(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnRButtonDownAndMove(IntPtr hevent) {
    return OnRButtonDownAndMove(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnLRButtonDownAndMove(IntPtr hevent) {
    return OnLRButtonDownAndMove(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnNoButtonDownAndMove(IntPtr hevent) {
    return OnNoButtonDownAndMove(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnTimer(IntPtr hevent) {
    return OnTimer(new HEventInfo(hevent, false));
  }

  public delegate IntPtr SwigDelegateHOpConstructRectangle_0();
  public delegate int SwigDelegateHOpConstructRectangle_1(IntPtr hevent);
  public delegate int SwigDelegateHOpConstructRectangle_2(IntPtr hevent);
  public delegate int SwigDelegateHOpConstructRectangle_3(IntPtr hevent);
  public delegate int SwigDelegateHOpConstructRectangle_4(IntPtr hevent);
  public delegate int SwigDelegateHOpConstructRectangle_5(IntPtr hevent);
  public delegate int SwigDelegateHOpConstructRectangle_6(IntPtr hevent);
  public delegate int SwigDelegateHOpConstructRectangle_7(IntPtr hevent);
  public delegate int SwigDelegateHOpConstructRectangle_8(IntPtr hevent);
  public delegate int SwigDelegateHOpConstructRectangle_9(IntPtr hevent);
  public delegate int SwigDelegateHOpConstructRectangle_10(IntPtr hevent);
  public delegate int SwigDelegateHOpConstructRectangle_11(IntPtr hevent);
  public delegate int SwigDelegateHOpConstructRectangle_12(IntPtr hevent);
  public delegate int SwigDelegateHOpConstructRectangle_13(IntPtr hevent);
  public delegate int SwigDelegateHOpConstructRectangle_14(IntPtr hevent);
  public delegate int SwigDelegateHOpConstructRectangle_15(IntPtr hevent);
  public delegate int SwigDelegateHOpConstructRectangle_16(IntPtr hevent);
  public delegate IntPtr SwigDelegateHOpConstructRectangle_17();
  public delegate bool SwigDelegateHOpConstructRectangle_18();
  public delegate string SwigDelegateHOpConstructRectangle_19();
  public delegate int SwigDelegateHOpConstructRectangle_20(IntPtr hevent);
  public delegate int SwigDelegateHOpConstructRectangle_21(IntPtr hevent);
  public delegate int SwigDelegateHOpConstructRectangle_22(IntPtr hevent);
  public delegate int SwigDelegateHOpConstructRectangle_23(IntPtr hevent);
  public delegate int SwigDelegateHOpConstructRectangle_24(IntPtr hevent);
  public delegate int SwigDelegateHOpConstructRectangle_25(IntPtr hevent);

  private SwigDelegateHOpConstructRectangle_0 swigDelegate0;
  private SwigDelegateHOpConstructRectangle_1 swigDelegate1;
  private SwigDelegateHOpConstructRectangle_2 swigDelegate2;
  private SwigDelegateHOpConstructRectangle_3 swigDelegate3;
  private SwigDelegateHOpConstructRectangle_4 swigDelegate4;
  private SwigDelegateHOpConstructRectangle_5 swigDelegate5;
  private SwigDelegateHOpConstructRectangle_6 swigDelegate6;
  private SwigDelegateHOpConstructRectangle_7 swigDelegate7;
  private SwigDelegateHOpConstructRectangle_8 swigDelegate8;
  private SwigDelegateHOpConstructRectangle_9 swigDelegate9;
  private SwigDelegateHOpConstructRectangle_10 swigDelegate10;
  private SwigDelegateHOpConstructRectangle_11 swigDelegate11;
  private SwigDelegateHOpConstructRectangle_12 swigDelegate12;
  private SwigDelegateHOpConstructRectangle_13 swigDelegate13;
  private SwigDelegateHOpConstructRectangle_14 swigDelegate14;
  private SwigDelegateHOpConstructRectangle_15 swigDelegate15;
  private SwigDelegateHOpConstructRectangle_16 swigDelegate16;
  private SwigDelegateHOpConstructRectangle_17 swigDelegate17;
  private SwigDelegateHOpConstructRectangle_18 swigDelegate18;
  private SwigDelegateHOpConstructRectangle_19 swigDelegate19;
  private SwigDelegateHOpConstructRectangle_20 swigDelegate20;
  private SwigDelegateHOpConstructRectangle_21 swigDelegate21;
  private SwigDelegateHOpConstructRectangle_22 swigDelegate22;
  private SwigDelegateHOpConstructRectangle_23 swigDelegate23;
  private SwigDelegateHOpConstructRectangle_24 swigDelegate24;
  private SwigDelegateHOpConstructRectangle_25 swigDelegate25;

  private static Type[] swigMethodTypes0 = new Type[] {  };
  private static Type[] swigMethodTypes1 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes2 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes3 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes4 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes5 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes6 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes7 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes8 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes9 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes10 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes11 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes12 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes13 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes14 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes15 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes16 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes17 = new Type[] {  };
  private static Type[] swigMethodTypes18 = new Type[] {  };
  private static Type[] swigMethodTypes19 = new Type[] {  };
  private static Type[] swigMethodTypes20 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes21 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes22 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes23 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes24 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes25 = new Type[] { typeof(HEventInfo) };
}
