/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

#if _M_X64
using MVO_POINTER_SIZED_INT = System.Int64;
using MVO_POINTER_SIZED_UINT = System.UInt64;
using ID_Key = System.Int64;
#else
using MVO_POINTER_SIZED_INT = System.Int32;
using MVO_POINTER_SIZED_UINT = System.UInt32;
using ID_Key = System.Int32;
#endif


public class HOpCameraZoomBox : HOpConstructRectangle {
  private HandleRef swigCPtr;

  public HOpCameraZoomBox(IntPtr cPtr, bool cMemoryOwn) : base(HCSMVOPINVOKE.HOpCameraZoomBoxUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(HOpCameraZoomBox obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~HOpCameraZoomBox() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          HCSMVOPINVOKE.delete_HOpCameraZoomBox(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public HOpCameraZoomBox(HBaseView view, int DoRepeat, int DoCapture) : this(HCSMVOPINVOKE.new_HOpCameraZoomBox__SWIG_0(HBaseView.getCPtr(view), DoRepeat, DoCapture), true) {
    SwigDirectorConnect();
  }

  public HOpCameraZoomBox(HBaseView view, int DoRepeat) : this(HCSMVOPINVOKE.new_HOpCameraZoomBox__SWIG_1(HBaseView.getCPtr(view), DoRepeat), true) {
    SwigDirectorConnect();
  }

  public HOpCameraZoomBox(HBaseView view) : this(HCSMVOPINVOKE.new_HOpCameraZoomBox__SWIG_2(HBaseView.getCPtr(view)), true) {
    SwigDirectorConnect();
  }

  public override string GetName() {
    string ret = ((this.GetType() == typeof(HOpCameraZoomBox)) ? HCSMVOPINVOKE.HOpCameraZoomBox_GetName(swigCPtr) : HCSMVOPINVOKE.HOpCameraZoomBox_GetNameSwigExplicitHOpCameraZoomBox(swigCPtr));
    return ret;
  }

  public override int OnLButtonUp(HEventInfo hevent) {
    int ret = ((this.GetType() == typeof(HOpCameraZoomBox)) ? HCSMVOPINVOKE.HOpCameraZoomBox_OnLButtonUp(swigCPtr, HEventInfo.getCPtr(hevent)) : HCSMVOPINVOKE.HOpCameraZoomBox_OnLButtonUpSwigExplicitHOpCameraZoomBox(swigCPtr, HEventInfo.getCPtr(hevent)));
    if (HCSMVOPINVOKE.SWIGPendingException.Pending) throw HCSMVOPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override int OnLButtonDblClk(HEventInfo hevent) {
    int ret = ((this.GetType() == typeof(HOpCameraZoomBox)) ? HCSMVOPINVOKE.HOpCameraZoomBox_OnLButtonDblClk(swigCPtr, HEventInfo.getCPtr(hevent)) : HCSMVOPINVOKE.HOpCameraZoomBox_OnLButtonDblClkSwigExplicitHOpCameraZoomBox(swigCPtr, HEventInfo.getCPtr(hevent)));
    if (HCSMVOPINVOKE.SWIGPendingException.Pending) throw HCSMVOPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetLightFollowsCamera(bool follow) {
    HCSMVOPINVOKE.HOpCameraZoomBox_SetLightFollowsCamera(swigCPtr, follow);
  }

  public bool GetLightFollowsCamera() {
    bool ret = HCSMVOPINVOKE.HOpCameraZoomBox_GetLightFollowsCamera(swigCPtr);
    return ret;
  }

  public override HBaseOperator Clone() {
    IntPtr cPtr = ((this.GetType() == typeof(HOpCameraZoomBox)) ? HCSMVOPINVOKE.HOpCameraZoomBox_Clone(swigCPtr) : HCSMVOPINVOKE.HOpCameraZoomBox_CloneSwigExplicitHOpCameraZoomBox(swigCPtr));
    HBaseOperator ret = (cPtr == IntPtr.Zero) ? null : new HBaseOperator(cPtr, false);
    return ret;
  }

  protected bool ComputeReasonableTarget(HPoint new_tar, HPoint min, HPoint max, HPoint tar_orig) {
    bool ret = HCSMVOPINVOKE.HOpCameraZoomBox_ComputeReasonableTarget(swigCPtr, HPoint.getCPtr(new_tar), HPoint.getCPtr(min), HPoint.getCPtr(max), HPoint.getCPtr(tar_orig));
    if (HCSMVOPINVOKE.SWIGPendingException.Pending) throw HCSMVOPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  protected void ComputeNewField(float[] width, float[] height, HPoint min, HPoint max, HPoint new_tar) {
    HCSMVOPINVOKE.HOpCameraZoomBox_ComputeNewField(swigCPtr, width, height, HPoint.getCPtr(min), HPoint.getCPtr(max), HPoint.getCPtr(new_tar));
    if (HCSMVOPINVOKE.SWIGPendingException.Pending) throw HCSMVOPINVOKE.SWIGPendingException.Retrieve();
  }

  protected bool m_LightFollowsCamera {
    set {
      HCSMVOPINVOKE.HOpCameraZoomBox_m_LightFollowsCamera_set(swigCPtr, value);
    } 
    get {
      bool ret = HCSMVOPINVOKE.HOpCameraZoomBox_m_LightFollowsCamera_get(swigCPtr);
      return ret;
    } 
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("CreateListenerManager", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateHOpCameraZoomBox_0(SwigDirectorCreateListenerManager);
    if (SwigDerivedClassHasMethod("OnLButtonDown", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateHOpCameraZoomBox_1(SwigDirectorOnLButtonDown);
    if (SwigDerivedClassHasMethod("OnMouseMove", swigMethodTypes2))
      swigDelegate2 = new SwigDelegateHOpCameraZoomBox_2(SwigDirectorOnMouseMove);
    if (SwigDerivedClassHasMethod("OnLButtonUp", swigMethodTypes3))
      swigDelegate3 = new SwigDelegateHOpCameraZoomBox_3(SwigDirectorOnLButtonUp);
    if (SwigDerivedClassHasMethod("OnLButtonDblClk", swigMethodTypes4))
      swigDelegate4 = new SwigDelegateHOpCameraZoomBox_4(SwigDirectorOnLButtonDblClk);
    if (SwigDerivedClassHasMethod("OnMButtonDown", swigMethodTypes5))
      swigDelegate5 = new SwigDelegateHOpCameraZoomBox_5(SwigDirectorOnMButtonDown);
    if (SwigDerivedClassHasMethod("OnMButtonUp", swigMethodTypes6))
      swigDelegate6 = new SwigDelegateHOpCameraZoomBox_6(SwigDirectorOnMButtonUp);
    if (SwigDerivedClassHasMethod("OnMButtonDblClk", swigMethodTypes7))
      swigDelegate7 = new SwigDelegateHOpCameraZoomBox_7(SwigDirectorOnMButtonDblClk);
    if (SwigDerivedClassHasMethod("OnRButtonDown", swigMethodTypes8))
      swigDelegate8 = new SwigDelegateHOpCameraZoomBox_8(SwigDirectorOnRButtonDown);
    if (SwigDerivedClassHasMethod("OnRButtonUp", swigMethodTypes9))
      swigDelegate9 = new SwigDelegateHOpCameraZoomBox_9(SwigDirectorOnRButtonUp);
    if (SwigDerivedClassHasMethod("OnRButtonDblClk", swigMethodTypes10))
      swigDelegate10 = new SwigDelegateHOpCameraZoomBox_10(SwigDirectorOnRButtonDblClk);
    if (SwigDerivedClassHasMethod("OnMouseWheel", swigMethodTypes11))
      swigDelegate11 = new SwigDelegateHOpCameraZoomBox_11(SwigDirectorOnMouseWheel);
    if (SwigDerivedClassHasMethod("OnKeyDown", swigMethodTypes12))
      swigDelegate12 = new SwigDelegateHOpCameraZoomBox_12(SwigDirectorOnKeyDown);
    if (SwigDerivedClassHasMethod("OnKeyUp", swigMethodTypes13))
      swigDelegate13 = new SwigDelegateHOpCameraZoomBox_13(SwigDirectorOnKeyUp);
    if (SwigDerivedClassHasMethod("OnTouchesDown", swigMethodTypes14))
      swigDelegate14 = new SwigDelegateHOpCameraZoomBox_14(SwigDirectorOnTouchesDown);
    if (SwigDerivedClassHasMethod("OnTouchesMove", swigMethodTypes15))
      swigDelegate15 = new SwigDelegateHOpCameraZoomBox_15(SwigDirectorOnTouchesMove);
    if (SwigDerivedClassHasMethod("OnTouchesUp", swigMethodTypes16))
      swigDelegate16 = new SwigDelegateHOpCameraZoomBox_16(SwigDirectorOnTouchesUp);
    if (SwigDerivedClassHasMethod("Clone", swigMethodTypes17))
      swigDelegate17 = new SwigDelegateHOpCameraZoomBox_17(SwigDirectorClone);
    if (SwigDerivedClassHasMethod("OperatorStarted", swigMethodTypes18))
      swigDelegate18 = new SwigDelegateHOpCameraZoomBox_18(SwigDirectorOperatorStarted);
    if (SwigDerivedClassHasMethod("GetName", swigMethodTypes19))
      swigDelegate19 = new SwigDelegateHOpCameraZoomBox_19(SwigDirectorGetName);
    if (SwigDerivedClassHasMethod("OnLButtonDownAndMove", swigMethodTypes20))
      swigDelegate20 = new SwigDelegateHOpCameraZoomBox_20(SwigDirectorOnLButtonDownAndMove);
    if (SwigDerivedClassHasMethod("OnMButtonDownAndMove", swigMethodTypes21))
      swigDelegate21 = new SwigDelegateHOpCameraZoomBox_21(SwigDirectorOnMButtonDownAndMove);
    if (SwigDerivedClassHasMethod("OnRButtonDownAndMove", swigMethodTypes22))
      swigDelegate22 = new SwigDelegateHOpCameraZoomBox_22(SwigDirectorOnRButtonDownAndMove);
    if (SwigDerivedClassHasMethod("OnLRButtonDownAndMove", swigMethodTypes23))
      swigDelegate23 = new SwigDelegateHOpCameraZoomBox_23(SwigDirectorOnLRButtonDownAndMove);
    if (SwigDerivedClassHasMethod("OnNoButtonDownAndMove", swigMethodTypes24))
      swigDelegate24 = new SwigDelegateHOpCameraZoomBox_24(SwigDirectorOnNoButtonDownAndMove);
    if (SwigDerivedClassHasMethod("OnTimer", swigMethodTypes25))
      swigDelegate25 = new SwigDelegateHOpCameraZoomBox_25(SwigDirectorOnTimer);
    HCSMVOPINVOKE.HOpCameraZoomBox_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2, swigDelegate3, swigDelegate4, swigDelegate5, swigDelegate6, swigDelegate7, swigDelegate8, swigDelegate9, swigDelegate10, swigDelegate11, swigDelegate12, swigDelegate13, swigDelegate14, swigDelegate15, swigDelegate16, swigDelegate17, swigDelegate18, swigDelegate19, swigDelegate20, swigDelegate21, swigDelegate22, swigDelegate23, swigDelegate24, swigDelegate25);
  }

  private bool SwigDerivedClassHasMethod(string methodName, Type[] methodTypes) {
    System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(HOpCameraZoomBox));
    return hasDerivedMethod;
  }

  private IntPtr SwigDirectorCreateListenerManager() {
    return HEventListener.getCPtr(CreateListenerManager()).Handle;
  }

  private int SwigDirectorOnLButtonDown(IntPtr hevent) {
    return OnLButtonDown(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnMouseMove(IntPtr hevent) {
    return OnMouseMove(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnLButtonUp(IntPtr hevent) {
    return OnLButtonUp(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnLButtonDblClk(IntPtr hevent) {
    return OnLButtonDblClk(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnMButtonDown(IntPtr hevent) {
    return OnMButtonDown(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnMButtonUp(IntPtr hevent) {
    return OnMButtonUp(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnMButtonDblClk(IntPtr hevent) {
    return OnMButtonDblClk(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnRButtonDown(IntPtr hevent) {
    return OnRButtonDown(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnRButtonUp(IntPtr hevent) {
    return OnRButtonUp(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnRButtonDblClk(IntPtr hevent) {
    return OnRButtonDblClk(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnMouseWheel(IntPtr hevent) {
    return OnMouseWheel(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnKeyDown(IntPtr hevent) {
    return OnKeyDown(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnKeyUp(IntPtr hevent) {
    return OnKeyUp(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnTouchesDown(IntPtr hevent) {
    return OnTouchesDown(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnTouchesMove(IntPtr hevent) {
    return OnTouchesMove(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnTouchesUp(IntPtr hevent) {
    return OnTouchesUp(new HEventInfo(hevent, false));
  }

  private IntPtr SwigDirectorClone() {
    return HBaseOperator.getCPtr(Clone()).Handle;
  }

  private bool SwigDirectorOperatorStarted() {
    return OperatorStarted();
  }

  private string SwigDirectorGetName() {
    return GetName();
  }

  private int SwigDirectorOnLButtonDownAndMove(IntPtr hevent) {
    return OnLButtonDownAndMove(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnMButtonDownAndMove(IntPtr hevent) {
    return OnMButtonDownAndMove(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnRButtonDownAndMove(IntPtr hevent) {
    return OnRButtonDownAndMove(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnLRButtonDownAndMove(IntPtr hevent) {
    return OnLRButtonDownAndMove(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnNoButtonDownAndMove(IntPtr hevent) {
    return OnNoButtonDownAndMove(new HEventInfo(hevent, false));
  }

  private int SwigDirectorOnTimer(IntPtr hevent) {
    return OnTimer(new HEventInfo(hevent, false));
  }

  public delegate IntPtr SwigDelegateHOpCameraZoomBox_0();
  public delegate int SwigDelegateHOpCameraZoomBox_1(IntPtr hevent);
  public delegate int SwigDelegateHOpCameraZoomBox_2(IntPtr hevent);
  public delegate int SwigDelegateHOpCameraZoomBox_3(IntPtr hevent);
  public delegate int SwigDelegateHOpCameraZoomBox_4(IntPtr hevent);
  public delegate int SwigDelegateHOpCameraZoomBox_5(IntPtr hevent);
  public delegate int SwigDelegateHOpCameraZoomBox_6(IntPtr hevent);
  public delegate int SwigDelegateHOpCameraZoomBox_7(IntPtr hevent);
  public delegate int SwigDelegateHOpCameraZoomBox_8(IntPtr hevent);
  public delegate int SwigDelegateHOpCameraZoomBox_9(IntPtr hevent);
  public delegate int SwigDelegateHOpCameraZoomBox_10(IntPtr hevent);
  public delegate int SwigDelegateHOpCameraZoomBox_11(IntPtr hevent);
  public delegate int SwigDelegateHOpCameraZoomBox_12(IntPtr hevent);
  public delegate int SwigDelegateHOpCameraZoomBox_13(IntPtr hevent);
  public delegate int SwigDelegateHOpCameraZoomBox_14(IntPtr hevent);
  public delegate int SwigDelegateHOpCameraZoomBox_15(IntPtr hevent);
  public delegate int SwigDelegateHOpCameraZoomBox_16(IntPtr hevent);
  public delegate IntPtr SwigDelegateHOpCameraZoomBox_17();
  public delegate bool SwigDelegateHOpCameraZoomBox_18();
  public delegate string SwigDelegateHOpCameraZoomBox_19();
  public delegate int SwigDelegateHOpCameraZoomBox_20(IntPtr hevent);
  public delegate int SwigDelegateHOpCameraZoomBox_21(IntPtr hevent);
  public delegate int SwigDelegateHOpCameraZoomBox_22(IntPtr hevent);
  public delegate int SwigDelegateHOpCameraZoomBox_23(IntPtr hevent);
  public delegate int SwigDelegateHOpCameraZoomBox_24(IntPtr hevent);
  public delegate int SwigDelegateHOpCameraZoomBox_25(IntPtr hevent);

  private SwigDelegateHOpCameraZoomBox_0 swigDelegate0;
  private SwigDelegateHOpCameraZoomBox_1 swigDelegate1;
  private SwigDelegateHOpCameraZoomBox_2 swigDelegate2;
  private SwigDelegateHOpCameraZoomBox_3 swigDelegate3;
  private SwigDelegateHOpCameraZoomBox_4 swigDelegate4;
  private SwigDelegateHOpCameraZoomBox_5 swigDelegate5;
  private SwigDelegateHOpCameraZoomBox_6 swigDelegate6;
  private SwigDelegateHOpCameraZoomBox_7 swigDelegate7;
  private SwigDelegateHOpCameraZoomBox_8 swigDelegate8;
  private SwigDelegateHOpCameraZoomBox_9 swigDelegate9;
  private SwigDelegateHOpCameraZoomBox_10 swigDelegate10;
  private SwigDelegateHOpCameraZoomBox_11 swigDelegate11;
  private SwigDelegateHOpCameraZoomBox_12 swigDelegate12;
  private SwigDelegateHOpCameraZoomBox_13 swigDelegate13;
  private SwigDelegateHOpCameraZoomBox_14 swigDelegate14;
  private SwigDelegateHOpCameraZoomBox_15 swigDelegate15;
  private SwigDelegateHOpCameraZoomBox_16 swigDelegate16;
  private SwigDelegateHOpCameraZoomBox_17 swigDelegate17;
  private SwigDelegateHOpCameraZoomBox_18 swigDelegate18;
  private SwigDelegateHOpCameraZoomBox_19 swigDelegate19;
  private SwigDelegateHOpCameraZoomBox_20 swigDelegate20;
  private SwigDelegateHOpCameraZoomBox_21 swigDelegate21;
  private SwigDelegateHOpCameraZoomBox_22 swigDelegate22;
  private SwigDelegateHOpCameraZoomBox_23 swigDelegate23;
  private SwigDelegateHOpCameraZoomBox_24 swigDelegate24;
  private SwigDelegateHOpCameraZoomBox_25 swigDelegate25;

  private static Type[] swigMethodTypes0 = new Type[] {  };
  private static Type[] swigMethodTypes1 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes2 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes3 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes4 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes5 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes6 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes7 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes8 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes9 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes10 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes11 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes12 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes13 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes14 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes15 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes16 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes17 = new Type[] {  };
  private static Type[] swigMethodTypes18 = new Type[] {  };
  private static Type[] swigMethodTypes19 = new Type[] {  };
  private static Type[] swigMethodTypes20 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes21 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes22 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes23 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes24 = new Type[] { typeof(HEventInfo) };
  private static Type[] swigMethodTypes25 = new Type[] { typeof(HEventInfo) };
}
