/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

#if _M_X64
using MVO_POINTER_SIZED_INT = System.Int64;
using MVO_POINTER_SIZED_UINT = System.UInt64;
using ID_Key = System.Int64;
#else
using MVO_POINTER_SIZED_INT = System.Int32;
using MVO_POINTER_SIZED_UINT = System.UInt32;
using ID_Key = System.Int32;
#endif


public class HPointKey : HPoint {
  private HandleRef swigCPtr;

  public HPointKey(IntPtr cPtr, bool cMemoryOwn) : base(HCSMVOPINVOKE.HPointKeyUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(HPointKey obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~HPointKey() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          HCSMVOPINVOKE.delete_HPointKey(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public HPointKey() : this(HCSMVOPINVOKE.new_HPointKey__SWIG_0(), true) {
  }

  public HPointKey(float X, float Y, float Z) : this(HCSMVOPINVOKE.new_HPointKey__SWIG_1(X, Y, Z), true) {
  }

  public HPointKey(float X, float Y) : this(HCSMVOPINVOKE.new_HPointKey__SWIG_2(X, Y), true) {
  }

  public HPointKey(HPoint p) : this(HCSMVOPINVOKE.new_HPointKey__SWIG_3(HPoint.getCPtr(p)), true) {
  }

}
