/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

#if _M_X64
using MVO_POINTER_SIZED_INT = System.Int64;
using MVO_POINTER_SIZED_UINT = System.UInt64;
using ID_Key = System.Int64;
#else
using MVO_POINTER_SIZED_INT = System.Int32;
using MVO_POINTER_SIZED_UINT = System.UInt32;
using ID_Key = System.Int32;
#endif


public class HPolyline : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public HPolyline(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  public static HandleRef getCPtr(HPolyline obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }
  
  public void owns_memory(bool ownMemory) {
	swigCMemOwn = ownMemory;
  }

  ~HPolyline() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          HCSMVOPINVOKE.delete_HPolyline(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public int m_PointCount {
    set {
      HCSMVOPINVOKE.HPolyline_m_PointCount_set(swigCPtr, value);
    } 
    get {
      int ret = HCSMVOPINVOKE.HPolyline_m_PointCount_get(swigCPtr);
      return ret;
    } 
  }

  public HPoint m_pHPointArray {
    get {
      IntPtr cPtr = HCSMVOPINVOKE.HPolyline_m_pHPointArray_get(swigCPtr);
      HPoint ret = (cPtr == IntPtr.Zero) ? null : new HPoint(cPtr, false);
      return ret;
    } 
  }

  public HPolyline m_pNextPolyline {
    set {
      HCSMVOPINVOKE.HPolyline_m_pNextPolyline_set(swigCPtr, HPolyline.getCPtr(value));
    } 
    get {
      IntPtr cPtr = HCSMVOPINVOKE.HPolyline_m_pNextPolyline_get(swigCPtr);
      HPolyline ret = (cPtr == IntPtr.Zero) ? null : new HPolyline(cPtr, false);
      return ret;
    } 
  }

  public HPolyline() : this(HCSMVOPINVOKE.new_HPolyline(), true) {
  }

}
