/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

#if _M_X64
using HLONG = System.Int64;
#else
using HLONG = System.Int32;
#endif


public class TK_Heuristics : BBaseOpcodeHandler {
  private HandleRef swigCPtr;

  internal TK_Heuristics(IntPtr cPtr, bool cMemoryOwn) : base(HCSBSTREAMPINVOKE.TK_HeuristicsUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(TK_Heuristics obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~TK_Heuristics() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          HCSBSTREAMPINVOKE.delete_TK_Heuristics(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public TK_Heuristics() : this(HCSBSTREAMPINVOKE.new_TK_Heuristics(), true) {
    SwigDirectorConnect();
  }

  public override TK_Status Read(BStreamFileToolkit tk) {
    TK_Status ret = (TK_Status)((this.GetType() == typeof(TK_Heuristics)) ? HCSBSTREAMPINVOKE.TK_Heuristics_Read(swigCPtr, BStreamFileToolkit.getCPtr(tk)) : HCSBSTREAMPINVOKE.TK_Heuristics_ReadSwigExplicitTK_Heuristics(swigCPtr, BStreamFileToolkit.getCPtr(tk)));
    if (HCSBSTREAMPINVOKE.SWIGPendingException.Pending) throw HCSBSTREAMPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override TK_Status Write(BStreamFileToolkit tk) {
    TK_Status ret = (TK_Status)((this.GetType() == typeof(TK_Heuristics)) ? HCSBSTREAMPINVOKE.TK_Heuristics_Write(swigCPtr, BStreamFileToolkit.getCPtr(tk)) : HCSBSTREAMPINVOKE.TK_Heuristics_WriteSwigExplicitTK_Heuristics(swigCPtr, BStreamFileToolkit.getCPtr(tk)));
    if (HCSBSTREAMPINVOKE.SWIGPendingException.Pending) throw HCSBSTREAMPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override TK_Status Clone(BStreamFileToolkit tk, SWIGTYPE_p_p_BBaseOpcodeHandler handler) {
    TK_Status ret = (TK_Status)((this.GetType() == typeof(TK_Heuristics)) ? HCSBSTREAMPINVOKE.TK_Heuristics_Clone(swigCPtr, BStreamFileToolkit.getCPtr(tk), SWIGTYPE_p_p_BBaseOpcodeHandler.getCPtr(handler)) : HCSBSTREAMPINVOKE.TK_Heuristics_CloneSwigExplicitTK_Heuristics(swigCPtr, BStreamFileToolkit.getCPtr(tk), SWIGTYPE_p_p_BBaseOpcodeHandler.getCPtr(handler)));
    if (HCSBSTREAMPINVOKE.SWIGPendingException.Pending) throw HCSBSTREAMPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public TK_Status ReadAscii(BStreamFileToolkit tk) {
    TK_Status ret = (TK_Status)HCSBSTREAMPINVOKE.TK_Heuristics_ReadAscii(swigCPtr, BStreamFileToolkit.getCPtr(tk));
    if (HCSBSTREAMPINVOKE.SWIGPendingException.Pending) throw HCSBSTREAMPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public TK_Status WriteAscii(BStreamFileToolkit tk) {
    TK_Status ret = (TK_Status)HCSBSTREAMPINVOKE.TK_Heuristics_WriteAscii(swigCPtr, BStreamFileToolkit.getCPtr(tk));
    if (HCSBSTREAMPINVOKE.SWIGPendingException.Pending) throw HCSBSTREAMPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void SetMask(int m) {
    HCSBSTREAMPINVOKE.TK_Heuristics_SetMask(swigCPtr, m);
  }

  public int GetMask() {
    int ret = HCSBSTREAMPINVOKE.TK_Heuristics_GetMask(swigCPtr);
    return ret;
  }

  public void SetValue(int v) {
    HCSBSTREAMPINVOKE.TK_Heuristics_SetValue(swigCPtr, v);
  }

  public int GetValue() {
    int ret = HCSBSTREAMPINVOKE.TK_Heuristics_GetValue(swigCPtr);
    return ret;
  }

  public void SetRelatedSelectionLimit(int r) {
    HCSBSTREAMPINVOKE.TK_Heuristics_SetRelatedSelectionLimit(swigCPtr, r);
  }

  public int GetRelatedSelectionLimit() {
    int ret = HCSBSTREAMPINVOKE.TK_Heuristics_GetRelatedSelectionLimit(swigCPtr);
    return ret;
  }

  public void SetInternalSelectionLimit(int i) {
    HCSBSTREAMPINVOKE.TK_Heuristics_SetInternalSelectionLimit(swigCPtr, i);
  }

  public int GetInternalSelectionLimit() {
    int ret = HCSBSTREAMPINVOKE.TK_Heuristics_GetInternalSelectionLimit(swigCPtr);
    return ret;
  }

  public void SetInternalShellSelectionLimit(int i) {
    HCSBSTREAMPINVOKE.TK_Heuristics_SetInternalShellSelectionLimit(swigCPtr, i);
  }

  public int GetInternalShellSelectionLimit() {
    int ret = HCSBSTREAMPINVOKE.TK_Heuristics_GetInternalShellSelectionLimit(swigCPtr);
    return ret;
  }

  public void SetInternalPolylineSelectionLimit(int i) {
    HCSBSTREAMPINVOKE.TK_Heuristics_SetInternalPolylineSelectionLimit(swigCPtr, i);
  }

  public int GetInternalPolylineSelectionLimit() {
    int ret = HCSBSTREAMPINVOKE.TK_Heuristics_GetInternalPolylineSelectionLimit(swigCPtr);
    return ret;
  }

  public void SetExtras(int e) {
    HCSBSTREAMPINVOKE.TK_Heuristics_SetExtras(swigCPtr, e);
  }

  public int GetExtras() {
    int ret = HCSBSTREAMPINVOKE.TK_Heuristics_GetExtras(swigCPtr);
    return ret;
  }

  public void SetCulling(int c) {
    HCSBSTREAMPINVOKE.TK_Heuristics_SetCulling(swigCPtr, c);
  }

  public int GetCulling() {
    int ret = HCSBSTREAMPINVOKE.TK_Heuristics_GetCulling(swigCPtr);
    return ret;
  }

  public void SetSelectionCulling(int c) {
    HCSBSTREAMPINVOKE.TK_Heuristics_SetSelectionCulling(swigCPtr, c);
  }

  public int GetSelectionCulling() {
    int ret = HCSBSTREAMPINVOKE.TK_Heuristics_GetSelectionCulling(swigCPtr);
    return ret;
  }

  public void SetPixelThreshold(int c) {
    HCSBSTREAMPINVOKE.TK_Heuristics_SetPixelThreshold(swigCPtr, c);
  }

  public int GetPixelThreshold() {
    int ret = HCSBSTREAMPINVOKE.TK_Heuristics_GetPixelThreshold(swigCPtr);
    return ret;
  }

  public void SetMaximumExtent(int c) {
    HCSBSTREAMPINVOKE.TK_Heuristics_SetMaximumExtent(swigCPtr, c);
  }

  public int GetMaximumExtent() {
    int ret = HCSBSTREAMPINVOKE.TK_Heuristics_GetMaximumExtent(swigCPtr);
    return ret;
  }

  public int GetMaximumExtentMode() {
    int ret = HCSBSTREAMPINVOKE.TK_Heuristics_GetMaximumExtentMode(swigCPtr);
    return ret;
  }

  public void SetMaximumExtentMode(int c) {
    HCSBSTREAMPINVOKE.TK_Heuristics_SetMaximumExtentMode(swigCPtr, c);
  }

  public int GetMaximumExtentLevel() {
    int ret = HCSBSTREAMPINVOKE.TK_Heuristics_GetMaximumExtentLevel(swigCPtr);
    return ret;
  }

  public void SetMaximumExtentLevel(int c) {
    HCSBSTREAMPINVOKE.TK_Heuristics_SetMaximumExtentLevel(swigCPtr, c);
  }

  public void SetHardExtent(int c) {
    HCSBSTREAMPINVOKE.TK_Heuristics_SetHardExtent(swigCPtr, c);
  }

  public int GetHardExtent() {
    int ret = HCSBSTREAMPINVOKE.TK_Heuristics_GetHardExtent(swigCPtr);
    return ret;
  }

  public IntPtr GetVector() {return HCSBSTREAMPINVOKE.TK_Heuristics_GetVector(swigCPtr);}

  public void SetVector(float x, float y, float z) {
    HCSBSTREAMPINVOKE.TK_Heuristics_SetVector__SWIG_0(swigCPtr, x, y, z);
  }

  public void SetVector(float[] v) {
    HCSBSTREAMPINVOKE.TK_Heuristics_SetVector__SWIG_1(swigCPtr, v);
  }

  public float GetVectorTolerance() {
    float ret = HCSBSTREAMPINVOKE.TK_Heuristics_GetVectorTolerance(swigCPtr);
    return ret;
  }

  public void SetVectorTolerance(float tol) {
    HCSBSTREAMPINVOKE.TK_Heuristics_SetVectorTolerance(swigCPtr, tol);
  }

  public void SetMaxDistance(float m) {
    HCSBSTREAMPINVOKE.TK_Heuristics_SetMaxDistance(swigCPtr, m);
  }

  public float GetMaxDistance() {
    float ret = HCSBSTREAMPINVOKE.TK_Heuristics_GetMaxDistance(swigCPtr);
    return ret;
  }

  public IntPtr GetViewVolume() {return HCSBSTREAMPINVOKE.TK_Heuristics_GetViewVolume(swigCPtr);}

  public void SetViewVolume(float ax, float ay, float az, float bx, float by, float bz) {
    HCSBSTREAMPINVOKE.TK_Heuristics_SetViewVolume__SWIG_0(swigCPtr, ax, ay, az, bx, by, bz);
  }

  public void SetViewVolume(float[] v) {
    HCSBSTREAMPINVOKE.TK_Heuristics_SetViewVolume__SWIG_1(swigCPtr, v);
  }

  public void SetOrderedWeightsMask(int c) {
    HCSBSTREAMPINVOKE.TK_Heuristics_SetOrderedWeightsMask(swigCPtr, c);
  }

  public int GetOrderedWeightsMask() {
    int ret = HCSBSTREAMPINVOKE.TK_Heuristics_GetOrderedWeightsMask(swigCPtr);
    return ret;
  }

  public void SetOrderedWeight(int index, float weight) {
    HCSBSTREAMPINVOKE.TK_Heuristics_SetOrderedWeight(swigCPtr, index, weight);
  }

  public float GetOrderedWeight(int index) {
    float ret = HCSBSTREAMPINVOKE.TK_Heuristics_GetOrderedWeight(swigCPtr, index);
    return ret;
  }

  public IntPtr GetOrderedWeights() {return HCSBSTREAMPINVOKE.TK_Heuristics_GetOrderedWeights__SWIG_0(swigCPtr);}

  public void SetSelectionLevel(int l) {
    HCSBSTREAMPINVOKE.TK_Heuristics_SetSelectionLevel(swigCPtr, l);
  }

  public int GetSelectionLevel() {
    int ret = HCSBSTREAMPINVOKE.TK_Heuristics_GetSelectionLevel(swigCPtr);
    return ret;
  }

  public void SetForceDefer(int l) {
    HCSBSTREAMPINVOKE.TK_Heuristics_SetForceDefer(swigCPtr, l);
  }

  public int GetForceDefer() {
    int ret = HCSBSTREAMPINVOKE.TK_Heuristics_GetForceDefer(swigCPtr);
    return ret;
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("Read", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateTK_Heuristics_0(SwigDirectorRead);
    if (SwigDerivedClassHasMethod("Write", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateTK_Heuristics_1(SwigDirectorWrite);
    if (SwigDerivedClassHasMethod("Execute", swigMethodTypes2))
      swigDelegate2 = new SwigDelegateTK_Heuristics_2(SwigDirectorExecute);
    if (SwigDerivedClassHasMethod("Interpret", swigMethodTypes3))
      swigDelegate3 = new SwigDelegateTK_Heuristics_3(SwigDirectorInterpret__SWIG_0);
    if (SwigDerivedClassHasMethod("Interpret", swigMethodTypes4))
      swigDelegate4 = new SwigDelegateTK_Heuristics_4(SwigDirectorInterpret__SWIG_1);
    if (SwigDerivedClassHasMethod("Interpret_special", swigMethodTypes5))
      swigDelegate5 = new SwigDelegateTK_Heuristics_5(SwigDirectorInterpret_special);
    if (SwigDerivedClassHasMethod("Reset", swigMethodTypes6))
      swigDelegate6 = new SwigDelegateTK_Heuristics_6(SwigDirectorReset);
    if (SwigDerivedClassHasMethod("Match_Instance", swigMethodTypes7))
      swigDelegate7 = new SwigDelegateTK_Heuristics_7(SwigDirectorMatch_Instance);
    if (SwigDerivedClassHasMethod("Clone", swigMethodTypes8))
      swigDelegate8 = new SwigDelegateTK_Heuristics_8(SwigDirectorClone);
    if (SwigDerivedClassHasMethod("NeedsContext", swigMethodTypes9))
      swigDelegate9 = new SwigDelegateTK_Heuristics_9(SwigDirectorNeedsContext);
    HCSBSTREAMPINVOKE.TK_Heuristics_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2, swigDelegate3, swigDelegate4, swigDelegate5, swigDelegate6, swigDelegate7, swigDelegate8, swigDelegate9);
  }

  private bool SwigDerivedClassHasMethod(string methodName, Type[] methodTypes) {
    System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(TK_Heuristics));
    return hasDerivedMethod;
  }

  private int SwigDirectorRead(IntPtr tk) {
    return (int)Read(new BStreamFileToolkit(tk, false));
  }

  private int SwigDirectorWrite(IntPtr tk) {
    return (int)Write(new BStreamFileToolkit(tk, false));
  }

  private int SwigDirectorExecute(IntPtr tk) {
    return (int)Execute(new BStreamFileToolkit(tk, false));
  }

  private int SwigDirectorInterpret__SWIG_0(IntPtr tk, int key, int variant) {
    return (int)Interpret(new BStreamFileToolkit(tk, false), key, variant);
  }

  private int SwigDirectorInterpret__SWIG_1(IntPtr tk, int key) {
    return (int)Interpret(new BStreamFileToolkit(tk, false), key);
  }

  private int SwigDirectorInterpret_special(IntPtr tk, int key, string special) {
    return (int)Interpret_special(new BStreamFileToolkit(tk, false), key, special);
  }

  private void SwigDirectorReset() {
    Reset();
  }

  private bool SwigDirectorMatch_Instance(IntPtr tk, IntPtr instance) {
    return Match_Instance(new BStreamFileToolkit(tk, false), (instance == IntPtr.Zero) ? null : new Recorded_Instance(instance, false));
  }

  private int SwigDirectorClone(IntPtr tk, IntPtr handler) {
    return (int)Clone(new BStreamFileToolkit(tk, false), (handler == IntPtr.Zero) ? null : new SWIGTYPE_p_p_BBaseOpcodeHandler(handler, false));
  }

  private bool SwigDirectorNeedsContext(IntPtr tk) {
    return NeedsContext(new BStreamFileToolkit(tk, false));
  }

  public delegate int SwigDelegateTK_Heuristics_0(IntPtr tk);
  public delegate int SwigDelegateTK_Heuristics_1(IntPtr tk);
  public delegate int SwigDelegateTK_Heuristics_2(IntPtr tk);
  public delegate int SwigDelegateTK_Heuristics_3(IntPtr tk, int key, int variant);
  public delegate int SwigDelegateTK_Heuristics_4(IntPtr tk, int key);
  public delegate int SwigDelegateTK_Heuristics_5(IntPtr tk, int key, string special);
  public delegate void SwigDelegateTK_Heuristics_6();
  public delegate bool SwigDelegateTK_Heuristics_7(IntPtr tk, IntPtr instance);
  public delegate int SwigDelegateTK_Heuristics_8(IntPtr tk, IntPtr handler);
  public delegate bool SwigDelegateTK_Heuristics_9(IntPtr tk);

  private SwigDelegateTK_Heuristics_0 swigDelegate0;
  private SwigDelegateTK_Heuristics_1 swigDelegate1;
  private SwigDelegateTK_Heuristics_2 swigDelegate2;
  private SwigDelegateTK_Heuristics_3 swigDelegate3;
  private SwigDelegateTK_Heuristics_4 swigDelegate4;
  private SwigDelegateTK_Heuristics_5 swigDelegate5;
  private SwigDelegateTK_Heuristics_6 swigDelegate6;
  private SwigDelegateTK_Heuristics_7 swigDelegate7;
  private SwigDelegateTK_Heuristics_8 swigDelegate8;
  private SwigDelegateTK_Heuristics_9 swigDelegate9;

  private static Type[] swigMethodTypes0 = new Type[] { typeof(BStreamFileToolkit) };
  private static Type[] swigMethodTypes1 = new Type[] { typeof(BStreamFileToolkit) };
  private static Type[] swigMethodTypes2 = new Type[] { typeof(BStreamFileToolkit) };
  private static Type[] swigMethodTypes3 = new Type[] { typeof(BStreamFileToolkit), typeof(int), typeof(int) };
  private static Type[] swigMethodTypes4 = new Type[] { typeof(BStreamFileToolkit), typeof(int) };
  private static Type[] swigMethodTypes5 = new Type[] { typeof(BStreamFileToolkit), typeof(int), typeof(string) };
  private static Type[] swigMethodTypes6 = new Type[] {  };
  private static Type[] swigMethodTypes7 = new Type[] { typeof(BStreamFileToolkit), typeof(Recorded_Instance) };
  private static Type[] swigMethodTypes8 = new Type[] { typeof(BStreamFileToolkit), typeof(SWIGTYPE_p_p_BBaseOpcodeHandler) };
  private static Type[] swigMethodTypes9 = new Type[] { typeof(BStreamFileToolkit) };
}
