/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public enum TKO_Texture_Param_Sources {
  TKO_Texture_Param_Source_U,
  TKO_Texture_Param_Source_UV,
  TKO_Texture_Param_Source_UVW,
  TKO_Texture_Param_Source_Object,
  TKO_Texture_Param_Source_World,
  TKO_Texture_Param_Source_Surface_Normal,
  TKO_Texture_Param_Source_Reflection_Vector,
  TKO_Texture_Param_Source_Natural_UV,
  TKO_Texture_Param_Source_Local_Pixels,
  TKO_Texture_Param_Source_Outer_Pixels,
  TKO_Texture_Param_Source_Local_Window,
  TKO_Texture_Param_Source_Outer_Window,
  TKO_Texture_Param_Source_Transmission_Vector,
  TKO_Texture_Param_Source_Sphere_Map,
  TKO_Texture_Param_Source_Cylinder_Map,
  TKO_Texture_Param_Source_Physical_Reflection_Vector
}
