/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops;

public class BByteStream {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected BByteStream(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BByteStream obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        HJSTREAMJNI.delete_BByteStream(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public BByteStream(int size, byte[] cptr, int bpv) {
    this(HJSTREAMJNI.new_BByteStream__SWIG_0(size, cptr, bpv), true);
  }

  public BByteStream() {
    this(HJSTREAMJNI.new_BByteStream__SWIG_1(), true);
  }

  public void put(int value) {
    HJSTREAMJNI.BByteStream_put(swigCPtr, this, value);
  }

  public void get(int[] value) {
    HJSTREAMJNI.BByteStream_get(swigCPtr, this, value);
  }

}
