/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops;

public class edgebreaker_header0 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected edgebreaker_header0(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(edgebreaker_header0 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        HJSTREAMJNI.delete_edgebreaker_header0(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setScheme(char value) {
    HJSTREAMJNI.edgebreaker_header0_scheme_set(swigCPtr, this, value);
  }

  public char getScheme() {
    return HJSTREAMJNI.edgebreaker_header0_scheme_get(swigCPtr, this);
  }

  public void setMtable_scheme(char value) {
    HJSTREAMJNI.edgebreaker_header0_mtable_scheme_set(swigCPtr, this, value);
  }

  public char getMtable_scheme() {
    return HJSTREAMJNI.edgebreaker_header0_mtable_scheme_get(swigCPtr, this);
  }

  public void setPoints_scheme(char value) {
    HJSTREAMJNI.edgebreaker_header0_points_scheme_set(swigCPtr, this, value);
  }

  public char getPoints_scheme() {
    return HJSTREAMJNI.edgebreaker_header0_points_scheme_get(swigCPtr, this);
  }

  public void setNormals_scheme(char value) {
    HJSTREAMJNI.edgebreaker_header0_normals_scheme_set(swigCPtr, this, value);
  }

  public char getNormals_scheme() {
    return HJSTREAMJNI.edgebreaker_header0_normals_scheme_get(swigCPtr, this);
  }

  public void setOpslen(int value) {
    HJSTREAMJNI.edgebreaker_header0_opslen_set(swigCPtr, this, value);
  }

  public int getOpslen() {
    return HJSTREAMJNI.edgebreaker_header0_opslen_get(swigCPtr, this);
  }

  public void setMtablelen(int value) {
    HJSTREAMJNI.edgebreaker_header0_mtablelen_set(swigCPtr, this, value);
  }

  public int getMtablelen() {
    return HJSTREAMJNI.edgebreaker_header0_mtablelen_get(swigCPtr, this);
  }

  public void setPointslen(int value) {
    HJSTREAMJNI.edgebreaker_header0_pointslen_set(swigCPtr, this, value);
  }

  public int getPointslen() {
    return HJSTREAMJNI.edgebreaker_header0_pointslen_get(swigCPtr, this);
  }

  public void setPcount(int value) {
    HJSTREAMJNI.edgebreaker_header0_pcount_set(swigCPtr, this, value);
  }

  public int getPcount() {
    return HJSTREAMJNI.edgebreaker_header0_pcount_get(swigCPtr, this);
  }

  public edgebreaker_header0() {
    this(HJSTREAMJNI.new_edgebreaker_header0(), true);
  }

}
