/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops;

public final class Instance_Options {
  public final static Instance_Options Instance_By_Tristrip = new Instance_Options("Instance_By_Tristrip", HJSTREAMJNI.Instance_By_Tristrip_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Instance_Options swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Instance_Options.class + " with value " + swigValue);
  }

  private Instance_Options(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Instance_Options(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Instance_Options(String swigName, Instance_Options swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Instance_Options[] swigValues = { Instance_By_Tristrip };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

