/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops;

public class IT_Index_Key_Extra {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IT_Index_Key_Extra(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IT_Index_Key_Extra obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        HJSTREAMJNI.delete_IT_Index_Key_Extra(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setM_variants(SWIGTYPE_p_a_2__int value) {
    HJSTREAMJNI.IT_Index_Key_Extra_m_variants_set(swigCPtr, this, SWIGTYPE_p_a_2__int.getCPtr(value));
  }

  public SWIGTYPE_p_a_2__int getM_variants() {
    long cPtr = HJSTREAMJNI.IT_Index_Key_Extra_m_variants_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_2__int(cPtr, false);
  }

  public void setM_options(int value) {
    HJSTREAMJNI.IT_Index_Key_Extra_m_options_set(swigCPtr, this, value);
  }

  public int getM_options() {
    return HJSTREAMJNI.IT_Index_Key_Extra_m_options_get(swigCPtr, this);
  }

  public void setM_bounds(SWIGTYPE_p_float value) {
    HJSTREAMJNI.IT_Index_Key_Extra_m_bounds_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getM_bounds() {
    long cPtr = HJSTREAMJNI.IT_Index_Key_Extra_m_bounds_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public IT_Index_Key_Extra() {
    this(HJSTREAMJNI.new_IT_Index_Key_Extra(), true);
  }

}
