/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops;

public class TK_Color extends BBaseOpcodeHandler {
  private long swigCPtr;

  protected TK_Color(long cPtr, boolean cMemoryOwn) {
    super(HJSTREAMJNI.SWIGTK_ColorUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TK_Color obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        HJSTREAMJNI.delete_TK_Color(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    HJSTREAMJNI.TK_Color_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    HJSTREAMJNI.TK_Color_change_ownership(this, swigCPtr, true);
  }

  protected void setM_mask(int value) {
    HJSTREAMJNI.TK_Color_m_mask_set(swigCPtr, this, value);
  }

  protected int getM_mask() {
    return HJSTREAMJNI.TK_Color_m_mask_get(swigCPtr, this);
  }

  protected void setM_channels(short value) {
    HJSTREAMJNI.TK_Color_m_channels_set(swigCPtr, this, value);
  }

  protected short getM_channels() {
    return HJSTREAMJNI.TK_Color_m_channels_get(swigCPtr, this);
  }

  protected void setM_gloss(float value) {
    HJSTREAMJNI.TK_Color_m_gloss_set(swigCPtr, this, value);
  }

  protected float getM_gloss() {
    return HJSTREAMJNI.TK_Color_m_gloss_get(swigCPtr, this);
  }

  protected void setM_index(float value) {
    HJSTREAMJNI.TK_Color_m_index_set(swigCPtr, this, value);
  }

  protected float getM_index() {
    return HJSTREAMJNI.TK_Color_m_index_get(swigCPtr, this);
  }

  protected void setM_substage(int value) {
    HJSTREAMJNI.TK_Color_m_substage_set(swigCPtr, this, value);
  }

  protected int getM_substage() {
    return HJSTREAMJNI.TK_Color_m_substage_get(swigCPtr, this);
  }

  public TK_Color() {
    this(HJSTREAMJNI.new_TK_Color(), true);
    HJSTREAMJNI.TK_Color_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public TK_Status Read(BStreamFileToolkit tk) {
    return TK_Status.swigToEnum((getClass() == TK_Color.class) ? HJSTREAMJNI.TK_Color_Read(swigCPtr, this, BStreamFileToolkit.getCPtr(tk), tk) : HJSTREAMJNI.TK_Color_ReadSwigExplicitTK_Color(swigCPtr, this, BStreamFileToolkit.getCPtr(tk), tk));
  }

  public TK_Status Write(BStreamFileToolkit tk) {
    return TK_Status.swigToEnum((getClass() == TK_Color.class) ? HJSTREAMJNI.TK_Color_Write(swigCPtr, this, BStreamFileToolkit.getCPtr(tk), tk) : HJSTREAMJNI.TK_Color_WriteSwigExplicitTK_Color(swigCPtr, this, BStreamFileToolkit.getCPtr(tk), tk));
  }

  public TK_Status Clone(BStreamFileToolkit tk, SWIGTYPE_p_p_BBaseOpcodeHandler handler) {
    return TK_Status.swigToEnum((getClass() == TK_Color.class) ? HJSTREAMJNI.TK_Color_Clone(swigCPtr, this, BStreamFileToolkit.getCPtr(tk), tk, SWIGTYPE_p_p_BBaseOpcodeHandler.getCPtr(handler)) : HJSTREAMJNI.TK_Color_CloneSwigExplicitTK_Color(swigCPtr, this, BStreamFileToolkit.getCPtr(tk), tk, SWIGTYPE_p_p_BBaseOpcodeHandler.getCPtr(handler)));
  }

  public TK_Status ReadAscii(BStreamFileToolkit tk) {
    return TK_Status.swigToEnum(HJSTREAMJNI.TK_Color_ReadAscii(swigCPtr, this, BStreamFileToolkit.getCPtr(tk), tk));
  }

  public TK_Status WriteAscii(BStreamFileToolkit tk) {
    return TK_Status.swigToEnum(HJSTREAMJNI.TK_Color_WriteAscii(swigCPtr, this, BStreamFileToolkit.getCPtr(tk), tk));
  }

  public void Reset() {
    if (getClass() == TK_Color.class) HJSTREAMJNI.TK_Color_Reset(swigCPtr, this); else HJSTREAMJNI.TK_Color_ResetSwigExplicitTK_Color(swigCPtr, this);
  }

  public void SetGeometry(int m) {
    HJSTREAMJNI.TK_Color_SetGeometry(swigCPtr, this, m);
  }

  public int GetGeometry() {
    return HJSTREAMJNI.TK_Color_GetGeometry(swigCPtr, this);
  }

  public void SetChannels(int c) {
    HJSTREAMJNI.TK_Color_SetChannels(swigCPtr, this, c);
  }

  public int GetChannels() {
    return HJSTREAMJNI.TK_Color_GetChannels(swigCPtr, this);
  }

  public void SetDiffuse(float r, float g, float b) {
    HJSTREAMJNI.TK_Color_SetDiffuse__SWIG_0(swigCPtr, this, r, g, b);
  }

  public void SetDiffuse(float[] rgb) {
    HJSTREAMJNI.TK_Color_SetDiffuse__SWIG_1(swigCPtr, this, rgb);
  }

  public void SetDiffuseName(String name) {
    HJSTREAMJNI.TK_Color_SetDiffuseName__SWIG_0(swigCPtr, this, name);
  }

  public void SetDiffuseName(int length) {
    HJSTREAMJNI.TK_Color_SetDiffuseName__SWIG_1(swigCPtr, this, length);
  }

  public String GetDiffuseName() {return HJSTREAMJNI.TK_Color_GetDiffuseName__SWIG_0(swigCPtr, this);}

  public void SetSpecular(float r, float g, float b) {
    HJSTREAMJNI.TK_Color_SetSpecular__SWIG_0(swigCPtr, this, r, g, b);
  }

  public void SetSpecular(float[] rgb) {
    HJSTREAMJNI.TK_Color_SetSpecular__SWIG_1(swigCPtr, this, rgb);
  }

  public void SetSpecularName(String name) {
    HJSTREAMJNI.TK_Color_SetSpecularName__SWIG_0(swigCPtr, this, name);
  }

  public void SetSpecularName(int length) {
    HJSTREAMJNI.TK_Color_SetSpecularName__SWIG_1(swigCPtr, this, length);
  }

  public String GetSpecularName() {return HJSTREAMJNI.TK_Color_GetSpecularName__SWIG_0(swigCPtr, this);}

  public void SetMirror(float r, float g, float b) {
    HJSTREAMJNI.TK_Color_SetMirror__SWIG_0(swigCPtr, this, r, g, b);
  }

  public void SetMirror(float[] rgb) {
    HJSTREAMJNI.TK_Color_SetMirror__SWIG_1(swigCPtr, this, rgb);
  }

  public void SetMirrorName(String name) {
    HJSTREAMJNI.TK_Color_SetMirrorName__SWIG_0(swigCPtr, this, name);
  }

  public void SetMirrorName(int length) {
    HJSTREAMJNI.TK_Color_SetMirrorName__SWIG_1(swigCPtr, this, length);
  }

  public String GetMirrorName() {return HJSTREAMJNI.TK_Color_GetMirrorName__SWIG_0(swigCPtr, this);}

  public void SetTransmission(float r, float g, float b) {
    HJSTREAMJNI.TK_Color_SetTransmission__SWIG_0(swigCPtr, this, r, g, b);
  }

  public void SetTransmission(float[] rgb) {
    HJSTREAMJNI.TK_Color_SetTransmission__SWIG_1(swigCPtr, this, rgb);
  }

  public void SetTransmissionName(String name) {
    HJSTREAMJNI.TK_Color_SetTransmissionName__SWIG_0(swigCPtr, this, name);
  }

  public void SetTransmissionName(int length) {
    HJSTREAMJNI.TK_Color_SetTransmissionName__SWIG_1(swigCPtr, this, length);
  }

  public String GetTransmissionName() {return HJSTREAMJNI.TK_Color_GetTransmissionName__SWIG_0(swigCPtr, this);}

  public void SetEmission(float r, float g, float b) {
    HJSTREAMJNI.TK_Color_SetEmission__SWIG_0(swigCPtr, this, r, g, b);
  }

  public void SetEmission(float[] rgb) {
    HJSTREAMJNI.TK_Color_SetEmission__SWIG_1(swigCPtr, this, rgb);
  }

  public void SetEmissionName(String name) {
    HJSTREAMJNI.TK_Color_SetEmissionName__SWIG_0(swigCPtr, this, name);
  }

  public void SetEmissionName(int length) {
    HJSTREAMJNI.TK_Color_SetEmissionName__SWIG_1(swigCPtr, this, length);
  }

  public String GetEmissionName() {return HJSTREAMJNI.TK_Color_GetEmissionName__SWIG_0(swigCPtr, this);}

  public void SetEnvironmentName(String name) {
    HJSTREAMJNI.TK_Color_SetEnvironmentName__SWIG_0(swigCPtr, this, name);
  }

  public void SetEnvironmentName(int length) {
    HJSTREAMJNI.TK_Color_SetEnvironmentName__SWIG_1(swigCPtr, this, length);
  }

  public String GetEnvironmentName() {return HJSTREAMJNI.TK_Color_GetEnvironmentName__SWIG_0(swigCPtr, this);}

  public void SetBumpName(String name) {
    HJSTREAMJNI.TK_Color_SetBumpName__SWIG_0(swigCPtr, this, name);
  }

  public void SetBumpName(int length) {
    HJSTREAMJNI.TK_Color_SetBumpName__SWIG_1(swigCPtr, this, length);
  }

  public String GetBumpName() {return HJSTREAMJNI.TK_Color_GetBumpName__SWIG_0(swigCPtr, this);}

  public void SetGloss(float g) {
    HJSTREAMJNI.TK_Color_SetGloss(swigCPtr, this, g);
  }

  public float GetGloss() {
    return HJSTREAMJNI.TK_Color_GetGloss(swigCPtr, this);
  }

  public void SetIndex(float i) {
    HJSTREAMJNI.TK_Color_SetIndex(swigCPtr, this, i);
  }

  public float GetIndex() {
    return HJSTREAMJNI.TK_Color_GetIndex(swigCPtr, this);
  }

}
