/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops;

public final class TK_File_Write_Options {
  public final static TK_File_Write_Options TK_Suppress_LOD = new TK_File_Write_Options("TK_Suppress_LOD", HJSTREAMJNI.TK_Suppress_LOD_get());
  public final static TK_File_Write_Options TK_Full_Resolution_Vertices = new TK_File_Write_Options("TK_Full_Resolution_Vertices", HJSTREAMJNI.TK_Full_Resolution_Vertices_get());
  public final static TK_File_Write_Options TK_Full_Resolution_Normals = new TK_File_Write_Options("TK_Full_Resolution_Normals", HJSTREAMJNI.TK_Full_Resolution_Normals_get());
  public final static TK_File_Write_Options TK_First_LOD_Is_Bounding_Box = new TK_File_Write_Options("TK_First_LOD_Is_Bounding_Box", HJSTREAMJNI.TK_First_LOD_Is_Bounding_Box_get());
  public final static TK_File_Write_Options TK_Force_Tags = new TK_File_Write_Options("TK_Force_Tags", HJSTREAMJNI.TK_Force_Tags_get());
  public final static TK_File_Write_Options TK_Disable_Priority_Heuristic = new TK_File_Write_Options("TK_Disable_Priority_Heuristic", HJSTREAMJNI.TK_Disable_Priority_Heuristic_get());
  public final static TK_File_Write_Options TK_Disable_Global_Compression = new TK_File_Write_Options("TK_Disable_Global_Compression", HJSTREAMJNI.TK_Disable_Global_Compression_get());
  public final static TK_File_Write_Options TK_Disable_Instancing = new TK_File_Write_Options("TK_Disable_Instancing", HJSTREAMJNI.TK_Disable_Instancing_get());
  public final static TK_File_Write_Options TK_Generate_Dictionary = new TK_File_Write_Options("TK_Generate_Dictionary", HJSTREAMJNI.TK_Generate_Dictionary_get());
  public final static TK_File_Write_Options TK_Connectivity_Compression = new TK_File_Write_Options("TK_Connectivity_Compression", HJSTREAMJNI.TK_Connectivity_Compression_get());
  public final static TK_File_Write_Options TK_Disable_Tristrips = new TK_File_Write_Options("TK_Disable_Tristrips", HJSTREAMJNI.TK_Disable_Tristrips_get());
  public final static TK_File_Write_Options TK_Disable_Compound_Primitives = new TK_File_Write_Options("TK_Disable_Compound_Primitives", HJSTREAMJNI.TK_Disable_Compound_Primitives_get());
  public final static TK_File_Write_Options TK_Global_Quantization = new TK_File_Write_Options("TK_Global_Quantization", HJSTREAMJNI.TK_Global_Quantization_get());
  public final static TK_File_Write_Options TK_Full_Resolution_Parameters = new TK_File_Write_Options("TK_Full_Resolution_Parameters", HJSTREAMJNI.TK_Full_Resolution_Parameters_get());
  public final static TK_File_Write_Options TK_Full_Resolution_Colors = new TK_File_Write_Options("TK_Full_Resolution_Colors", HJSTREAMJNI.TK_Full_Resolution_Colors_get());
  public final static TK_File_Write_Options TK_Full_Resolution_Index_Colors = new TK_File_Write_Options("TK_Full_Resolution_Index_Colors", HJSTREAMJNI.TK_Full_Resolution_Index_Colors_get());
  public final static TK_File_Write_Options TK_Communicator_Mode = new TK_File_Write_Options("TK_Communicator_Mode", HJSTREAMJNI.TK_Communicator_Mode_get());
  public final static TK_File_Write_Options TK_Full_Resolution = new TK_File_Write_Options("TK_Full_Resolution", HJSTREAMJNI.TK_Full_Resolution_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TK_File_Write_Options swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TK_File_Write_Options.class + " with value " + swigValue);
  }

  private TK_File_Write_Options(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TK_File_Write_Options(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TK_File_Write_Options(String swigName, TK_File_Write_Options swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TK_File_Write_Options[] swigValues = { TK_Suppress_LOD, TK_Full_Resolution_Vertices, TK_Full_Resolution_Normals, TK_First_LOD_Is_Bounding_Box, TK_Force_Tags, TK_Disable_Priority_Heuristic, TK_Disable_Global_Compression, TK_Disable_Instancing, TK_Generate_Dictionary, TK_Connectivity_Compression, TK_Disable_Tristrips, TK_Disable_Compound_Primitives, TK_Global_Quantization, TK_Full_Resolution_Parameters, TK_Full_Resolution_Colors, TK_Full_Resolution_Index_Colors, TK_Communicator_Mode, TK_Full_Resolution };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

