/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops;

public class TK_Terminator extends BBaseOpcodeHandler {
  private long swigCPtr;

  protected TK_Terminator(long cPtr, boolean cMemoryOwn) {
    super(HJSTREAMJNI.SWIGTK_TerminatorUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TK_Terminator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        HJSTREAMJNI.delete_TK_Terminator(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    HJSTREAMJNI.TK_Terminator_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    HJSTREAMJNI.TK_Terminator_change_ownership(this, swigCPtr, true);
  }

  public TK_Terminator(char opcode, boolean is_file_terminator) {
    this(HJSTREAMJNI.new_TK_Terminator__SWIG_0(opcode, is_file_terminator), true);
    HJSTREAMJNI.TK_Terminator_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public TK_Terminator(char opcode) {
    this(HJSTREAMJNI.new_TK_Terminator__SWIG_1(opcode), true);
    HJSTREAMJNI.TK_Terminator_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public TK_Status Read(BStreamFileToolkit tk) {
    return TK_Status.swigToEnum((getClass() == TK_Terminator.class) ? HJSTREAMJNI.TK_Terminator_Read(swigCPtr, this, BStreamFileToolkit.getCPtr(tk), tk) : HJSTREAMJNI.TK_Terminator_ReadSwigExplicitTK_Terminator(swigCPtr, this, BStreamFileToolkit.getCPtr(tk), tk));
  }

  public TK_Status Write(BStreamFileToolkit tk) {
    return TK_Status.swigToEnum((getClass() == TK_Terminator.class) ? HJSTREAMJNI.TK_Terminator_Write(swigCPtr, this, BStreamFileToolkit.getCPtr(tk), tk) : HJSTREAMJNI.TK_Terminator_WriteSwigExplicitTK_Terminator(swigCPtr, this, BStreamFileToolkit.getCPtr(tk), tk));
  }

  public TK_Status Execute(BStreamFileToolkit tk) {
    return TK_Status.swigToEnum((getClass() == TK_Terminator.class) ? HJSTREAMJNI.TK_Terminator_Execute(swigCPtr, this, BStreamFileToolkit.getCPtr(tk), tk) : HJSTREAMJNI.TK_Terminator_ExecuteSwigExplicitTK_Terminator(swigCPtr, this, BStreamFileToolkit.getCPtr(tk), tk));
  }

  public TK_Status ReadAscii(BStreamFileToolkit tk) {
    return TK_Status.swigToEnum(HJSTREAMJNI.TK_Terminator_ReadAscii(swigCPtr, this, BStreamFileToolkit.getCPtr(tk), tk));
  }

  public TK_Status WriteAscii(BStreamFileToolkit tk) {
    return TK_Status.swigToEnum(HJSTREAMJNI.TK_Terminator_WriteAscii(swigCPtr, this, BStreamFileToolkit.getCPtr(tk), tk));
  }

  protected void setM_terminate_file(boolean value) {
    HJSTREAMJNI.TK_Terminator_m_terminate_file_set(swigCPtr, this, value);
  }

  protected boolean getM_terminate_file() {
    return HJSTREAMJNI.TK_Terminator_m_terminate_file_get(swigCPtr, this);
  }

}
