/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops;

public final class TKO_Font_Options {
  public final static TKO_Font_Options TKO_Font_Names = new TKO_Font_Options("TKO_Font_Names", HJSTREAMJNI.TKO_Font_Names_get());
  public final static TKO_Font_Options TKO_Font_Size = new TKO_Font_Options("TKO_Font_Size", HJSTREAMJNI.TKO_Font_Size_get());
  public final static TKO_Font_Options TKO_Font_Size_Tolerance = new TKO_Font_Options("TKO_Font_Size_Tolerance", HJSTREAMJNI.TKO_Font_Size_Tolerance_get());
  public final static TKO_Font_Options TKO_Font_Transforms = new TKO_Font_Options("TKO_Font_Transforms", HJSTREAMJNI.TKO_Font_Transforms_get());
  public final static TKO_Font_Options TKO_Font_Rotation = new TKO_Font_Options("TKO_Font_Rotation", HJSTREAMJNI.TKO_Font_Rotation_get());
  public final static TKO_Font_Options TKO_Font_Slant = new TKO_Font_Options("TKO_Font_Slant", HJSTREAMJNI.TKO_Font_Slant_get());
  public final static TKO_Font_Options TKO_Font_Width_Scale = new TKO_Font_Options("TKO_Font_Width_Scale", HJSTREAMJNI.TKO_Font_Width_Scale_get());
  public final static TKO_Font_Options TKO_Font_Extended = new TKO_Font_Options("TKO_Font_Extended", HJSTREAMJNI.TKO_Font_Extended_get());
  public final static TKO_Font_Options TKO_Font_Extended_Mask = new TKO_Font_Options("TKO_Font_Extended_Mask", HJSTREAMJNI.TKO_Font_Extended_Mask_get());
  public final static TKO_Font_Options TKO_Font_Extended_Shift = new TKO_Font_Options("TKO_Font_Extended_Shift", HJSTREAMJNI.TKO_Font_Extended_Shift_get());
  public final static TKO_Font_Options TKO_Font_Extra_Space = new TKO_Font_Options("TKO_Font_Extra_Space", HJSTREAMJNI.TKO_Font_Extra_Space_get());
  public final static TKO_Font_Options TKO_Font_Line_Spacing = new TKO_Font_Options("TKO_Font_Line_Spacing", HJSTREAMJNI.TKO_Font_Line_Spacing_get());
  public final static TKO_Font_Options TKO_Font_Outline = new TKO_Font_Options("TKO_Font_Outline", HJSTREAMJNI.TKO_Font_Outline_get());
  public final static TKO_Font_Options TKO_Font_Underline = new TKO_Font_Options("TKO_Font_Underline", HJSTREAMJNI.TKO_Font_Underline_get());
  public final static TKO_Font_Options TKO_Font_Strikethrough = new TKO_Font_Options("TKO_Font_Strikethrough", HJSTREAMJNI.TKO_Font_Strikethrough_get());
  public final static TKO_Font_Options TKO_Font_Overline = new TKO_Font_Options("TKO_Font_Overline", HJSTREAMJNI.TKO_Font_Overline_get());
  public final static TKO_Font_Options TKO_Font_Uniform_Spacing = new TKO_Font_Options("TKO_Font_Uniform_Spacing", HJSTREAMJNI.TKO_Font_Uniform_Spacing_get());
  public final static TKO_Font_Options TKO_Font_Extended2 = new TKO_Font_Options("TKO_Font_Extended2", HJSTREAMJNI.TKO_Font_Extended2_get());
  public final static TKO_Font_Options TKO_Font_Extended2_Mask = new TKO_Font_Options("TKO_Font_Extended2_Mask", HJSTREAMJNI.TKO_Font_Extended2_Mask_get());
  public final static TKO_Font_Options TKO_Font_Extended2_Shift = new TKO_Font_Options("TKO_Font_Extended2_Shift", HJSTREAMJNI.TKO_Font_Extended2_Shift_get());
  public final static TKO_Font_Options TKO_Font_Greeking_Limit = new TKO_Font_Options("TKO_Font_Greeking_Limit", HJSTREAMJNI.TKO_Font_Greeking_Limit_get());
  public final static TKO_Font_Options TKO_Font_Fill_Edges = new TKO_Font_Options("TKO_Font_Fill_Edges", HJSTREAMJNI.TKO_Font_Fill_Edges_get());
  public final static TKO_Font_Options TKO_Font_Bold = new TKO_Font_Options("TKO_Font_Bold", HJSTREAMJNI.TKO_Font_Bold_get());
  public final static TKO_Font_Options TKO_Font_Italic = new TKO_Font_Options("TKO_Font_Italic", HJSTREAMJNI.TKO_Font_Italic_get());
  public final static TKO_Font_Options TKO_Font_Renderer = new TKO_Font_Options("TKO_Font_Renderer", HJSTREAMJNI.TKO_Font_Renderer_get());
  public final static TKO_Font_Options TKO_Font_Greeking_Mode = new TKO_Font_Options("TKO_Font_Greeking_Mode", HJSTREAMJNI.TKO_Font_Greeking_Mode_get());
  public final static TKO_Font_Options TKO_Font_Preference = new TKO_Font_Options("TKO_Font_Preference", HJSTREAMJNI.TKO_Font_Preference_get());
  public final static TKO_Font_Options TKO_Font_Layout = new TKO_Font_Options("TKO_Font_Layout", HJSTREAMJNI.TKO_Font_Layout_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TKO_Font_Options swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TKO_Font_Options.class + " with value " + swigValue);
  }

  private TKO_Font_Options(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TKO_Font_Options(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TKO_Font_Options(String swigName, TKO_Font_Options swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TKO_Font_Options[] swigValues = { TKO_Font_Names, TKO_Font_Size, TKO_Font_Size_Tolerance, TKO_Font_Transforms, TKO_Font_Rotation, TKO_Font_Slant, TKO_Font_Width_Scale, TKO_Font_Extended, TKO_Font_Extended_Mask, TKO_Font_Extended_Shift, TKO_Font_Extra_Space, TKO_Font_Line_Spacing, TKO_Font_Outline, TKO_Font_Underline, TKO_Font_Strikethrough, TKO_Font_Overline, TKO_Font_Uniform_Spacing, TKO_Font_Extended2, TKO_Font_Extended2_Mask, TKO_Font_Extended2_Shift, TKO_Font_Greeking_Limit, TKO_Font_Fill_Edges, TKO_Font_Bold, TKO_Font_Italic, TKO_Font_Renderer, TKO_Font_Greeking_Mode, TKO_Font_Preference, TKO_Font_Layout };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

