/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops;

public final class TKO_Generic_Size_Units {
  public final static TKO_Generic_Size_Units TKO_Generic_Size_Object = new TKO_Generic_Size_Units("TKO_Generic_Size_Object");
  public final static TKO_Generic_Size_Units TKO_Generic_Size_Screen = new TKO_Generic_Size_Units("TKO_Generic_Size_Screen");
  public final static TKO_Generic_Size_Units TKO_Generic_Size_Window = new TKO_Generic_Size_Units("TKO_Generic_Size_Window");
  public final static TKO_Generic_Size_Units TKO_Generic_Size_Points = new TKO_Generic_Size_Units("TKO_Generic_Size_Points");
  public final static TKO_Generic_Size_Units TKO_Generic_Size_Pixels = new TKO_Generic_Size_Units("TKO_Generic_Size_Pixels");
  public final static TKO_Generic_Size_Units TKO_Generic_Size_Percent = new TKO_Generic_Size_Units("TKO_Generic_Size_Percent");
  public final static TKO_Generic_Size_Units TKO_Generic_Size_World = new TKO_Generic_Size_Units("TKO_Generic_Size_World");
  public final static TKO_Generic_Size_Units TKO_Generic_Size_Unspecified = new TKO_Generic_Size_Units("TKO_Generic_Size_Unspecified");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TKO_Generic_Size_Units swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TKO_Generic_Size_Units.class + " with value " + swigValue);
  }

  private TKO_Generic_Size_Units(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TKO_Generic_Size_Units(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TKO_Generic_Size_Units(String swigName, TKO_Generic_Size_Units swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TKO_Generic_Size_Units[] swigValues = { TKO_Generic_Size_Object, TKO_Generic_Size_Screen, TKO_Generic_Size_Window, TKO_Generic_Size_Points, TKO_Generic_Size_Pixels, TKO_Generic_Size_Percent, TKO_Generic_Size_World, TKO_Generic_Size_Unspecified };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

