/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops;

public final class TKO_Compression {
  public final static TKO_Compression TKO_Compression_None = new TKO_Compression("TKO_Compression_None", HJSTREAMJNI.TKO_Compression_None_get());
  public final static TKO_Compression TKO_Compression_RLE = new TKO_Compression("TKO_Compression_RLE", HJSTREAMJNI.TKO_Compression_RLE_get());
  public final static TKO_Compression TKO_Compression_JPEG = new TKO_Compression("TKO_Compression_JPEG", HJSTREAMJNI.TKO_Compression_JPEG_get());
  public final static TKO_Compression TKO_Compression_DXT = new TKO_Compression("TKO_Compression_DXT", HJSTREAMJNI.TKO_Compression_DXT_get());
  public final static TKO_Compression TKO_Compression_TARGA = new TKO_Compression("TKO_Compression_TARGA", HJSTREAMJNI.TKO_Compression_TARGA_get());
  public final static TKO_Compression TKO_Compression_PNG = new TKO_Compression("TKO_Compression_PNG", HJSTREAMJNI.TKO_Compression_PNG_get());
  public final static TKO_Compression TKO_Compression_Reference = new TKO_Compression("TKO_Compression_Reference", HJSTREAMJNI.TKO_Compression_Reference_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TKO_Compression swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TKO_Compression.class + " with value " + swigValue);
  }

  private TKO_Compression(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TKO_Compression(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TKO_Compression(String swigName, TKO_Compression swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TKO_Compression[] swigValues = { TKO_Compression_None, TKO_Compression_RLE, TKO_Compression_JPEG, TKO_Compression_DXT, TKO_Compression_TARGA, TKO_Compression_PNG, TKO_Compression_Reference };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

