/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops;

public final class TKO_Text_Encodings {
  public final static TKO_Text_Encodings TKO_Enc_ISO_Latin_One = new TKO_Text_Encodings("TKO_Enc_ISO_Latin_One");
  public final static TKO_Text_Encodings TKO_Enc_ISO_Latin = new TKO_Text_Encodings("TKO_Enc_ISO_Latin");
  public final static TKO_Text_Encodings TKO_Enc_JEC = new TKO_Text_Encodings("TKO_Enc_JEC");
  public final static TKO_Text_Encodings TKO_Enc_EUC = new TKO_Text_Encodings("TKO_Enc_EUC");
  public final static TKO_Text_Encodings TKO_Enc_Raw_16 = new TKO_Text_Encodings("TKO_Enc_Raw_16");
  public final static TKO_Text_Encodings TKO_Enc_Unicode = new TKO_Text_Encodings("TKO_Enc_Unicode");
  public final static TKO_Text_Encodings TKO_Enc_Unicode32 = new TKO_Text_Encodings("TKO_Enc_Unicode32");
  public final static TKO_Text_Encodings TKO_Enc_UTF8 = new TKO_Text_Encodings("TKO_Enc_UTF8");
  public final static TKO_Text_Encodings TKO_Enc_UTF16 = new TKO_Text_Encodings("TKO_Enc_UTF16");
  public final static TKO_Text_Encodings TKO_Enc_UTF32 = new TKO_Text_Encodings("TKO_Enc_UTF32");
  public final static TKO_Text_Encodings TKO_Enc_WCS = new TKO_Text_Encodings("TKO_Enc_WCS");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TKO_Text_Encodings swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TKO_Text_Encodings.class + " with value " + swigValue);
  }

  private TKO_Text_Encodings(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TKO_Text_Encodings(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TKO_Text_Encodings(String swigName, TKO_Text_Encodings swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TKO_Text_Encodings[] swigValues = { TKO_Enc_ISO_Latin_One, TKO_Enc_ISO_Latin, TKO_Enc_JEC, TKO_Enc_EUC, TKO_Enc_Raw_16, TKO_Enc_Unicode, TKO_Enc_Unicode32, TKO_Enc_UTF8, TKO_Enc_UTF16, TKO_Enc_UTF32, TKO_Enc_WCS };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

