/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.techsoft.hoops;

public class varstream {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected varstream(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(varstream obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        HJSTREAMJNI.delete_varstream(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void get_data(int[] values, int count) {
    HJSTREAMJNI.varstream_get_data(swigCPtr, this, values, count);
  }

  public void get_rdata(int[] values, int count) {
    HJSTREAMJNI.varstream_get_rdata(swigCPtr, this, values, count);
  }

  public void setAllocated(int value) {
    HJSTREAMJNI.varstream_allocated_set(swigCPtr, this, value);
  }

  public int getAllocated() {
    return HJSTREAMJNI.varstream_allocated_get(swigCPtr, this);
  }

  public void setUsed(int value) {
    HJSTREAMJNI.varstream_used_set(swigCPtr, this, value);
  }

  public int getUsed() {
    return HJSTREAMJNI.varstream_used_get(swigCPtr, this);
  }

  public void setBit(int value) {
    HJSTREAMJNI.varstream_bit_set(swigCPtr, this, value);
  }

  public int getBit() {
    return HJSTREAMJNI.varstream_bit_get(swigCPtr, this);
  }

  public void setRused(int value) {
    HJSTREAMJNI.varstream_rused_set(swigCPtr, this, value);
  }

  public int getRused() {
    return HJSTREAMJNI.varstream_rused_get(swigCPtr, this);
  }

  public void setRbit(int value) {
    HJSTREAMJNI.varstream_rbit_set(swigCPtr, this, value);
  }

  public int getRbit() {
    return HJSTREAMJNI.varstream_rbit_get(swigCPtr, this);
  }

  public void setCan_reallocate(int value) {
    HJSTREAMJNI.varstream_can_reallocate_set(swigCPtr, this, value);
  }

  public int getCan_reallocate() {
    return HJSTREAMJNI.varstream_can_reallocate_get(swigCPtr, this);
  }

  public void setStatus(int value) {
    HJSTREAMJNI.varstream_status_set(swigCPtr, this, value);
  }

  public int getStatus() {
    return HJSTREAMJNI.varstream_status_get(swigCPtr, this);
  }

  public void setMask(SWIGTYPE_p_unsigned_int value) {
    HJSTREAMJNI.varstream_mask_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getMask() {
    long cPtr = HJSTREAMJNI.varstream_mask_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public void setRange(SWIGTYPE_p_unsigned_int value) {
    HJSTREAMJNI.varstream_range_set(swigCPtr, this, SWIGTYPE_p_unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_int getRange() {
    long cPtr = HJSTREAMJNI.varstream_range_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
  }

  public varstream() {
    this(HJSTREAMJNI.new_varstream(), true);
  }

}
